/* ══════════════════════════════════
   CONFIGURATION — RARETÉS
══════════════════════════════════ */
const RARITIES = {
  'commun':     { label: 'Commun',      color: '#59d059' },
  'rare':       { label: 'Rare',        color: '#2a5fa8' },
  'epique':     { label: 'Épique',      color: '#6a3daa' },
  'legendaire': { label: 'Légendaire',  color: '#d7af5f' },
  'mythique':   { label: 'Mythique',    color: '#f5b5e4' },
  'godlike':    { label: 'Godlike',     color: '#a83020' },
};

/* ══════════════════════════════════
   CONFIGURATION — CATÉGORIES
══════════════════════════════════ */
const CATEGORIES = {
  materiaux:       { label: 'Matériaux',          emoji: '🧱' },
  quete:           { label: 'Objets de Quête',    emoji: '📜' },
  minerais:        { label: 'Minerais',           emoji: '⛏️' },
  nourriture:      { label: 'Nourriture',         emoji: '🍖' },
  consommable:     { label: 'Consommables',       emoji: '🧪' },
  arme:            { label: 'Armes',              emoji: '⚔️'  },
  armure:          { label: 'Armures',            emoji: '🛡️'  },
  accessoire:      { label: 'Accessoires',        emoji: '💍'  },
  outils:          { label: 'Outils',             emoji: '🛠️' },
  clef:            { label: 'Clefs',              emoji: '🗝️'  },
  rune:            { label: 'Runes',              emoji: '🔮'  },
};

const ITEMS = [
  /* ── PALIER 1 ── */
  {
    id:       'dague_dentrainement',
    name:     "Dague d'Entrainement",
    rarity:   'commun',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/dague_dentrainement.png",
    lore:     "Forgée pour ceux qui n'ont encore rien prouvé.",
    tags:     ['Arme', 'Dague', 'Palier 1', 'Commun'],
    obtain:   "Obtenable dans le tutoriel"
  },
  {
    id:       'épée_dentrainement',
    name:     "Épée d'Entrainement",
    rarity:   'commun',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/epee_dentrainement.png",
    lore:     "Petite épée un peu rouillée parfaite pour s'entraîner ou pour démarrer son aventure.",
    tags:     ['Arme', 'Épée', 'Palier 1', 'Commun'],
    obtain:   "Obtenable par les Marchands d'Équipement"
  },
  {
    id:       'bouclier_de_pacotille',
    name:     "Bouclier de Pacotille",
    rarity:   'commun',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/bouclier_de_pacotille.png",
    lore:     "Un vieux bouclier. Il bloque encore à peu près.",
    tags:     ['Arme', 'Bouclier', 'Rondache', 'Palier 1', 'Commun'],
    obtain:   "Obtenable par les Marchands d'Équipement"
  },
  {
    id:       'dague_délabrée',
    name:     "Dague Délabrée",
    rarity:   'commun',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/dague_delabree.png",
    lore:     "Dague bien délabrée, même un coup sur du bois et l'épée peut être détruite.",
    tags:     ['Arme', 'Dague', 'Palier 1', 'Commun'],
    obtain:   "Obtenable par les Marchands d'Équipement"
  },
  {
    id:       'arc_courbé',
    name:     "Arc Courbé",
    rarity:   'commun',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/arc_courbe.png",
    lore:     "Un arc rudimentaire utilisé par les premiers tireurs.",
    tags:     ['Arme', 'Arc', 'Palier 1', 'Commun'],
    obtain:   "Obtenable par les Marchands d'Équipement"
  },
  {
    id:       'bâton_médiocre',
    name:     "Bâton Médiocre",
    rarity:   'commun',
    category: 'arme',
    palier:   1,
    images:   ["../img/compendium/textures/weapons/baton_mediocre_mage.png", "../img/compendium/textures/weapons/baton_mediocre_shaman.png"],
    lore:     "Un bâton d'apprentissage magique inoffensif, mais porteur d'énergie.",
    tags:     ['Arme', 'Bâton', 'Palier 1', 'Commun'],
    obtain:   "Obtenable par les Marchands d'Équipement"
  },
  {
    id:       'grimoire_délié',
    name:     "Grimoire Délié",
    rarity:   'commun',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/grimoire_delie-sauvage.png",
    lore:     "Un livre incomplet débordant de magie.",
    tags:     ['Arme', 'Catalyseur', 'Palier 1', 'Commun'],
    obtain:   "Obtenable par les Marchands d'Équipement"
  },
  {
    id:       'grimoire_sauvage',
    name:     "Grimoire Sauvage",
    rarity:   'commun',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/grimoire_delie-sauvage.png",
    lore:     "Un livre incomplet débordant de magie.",
    tags:     ['Arme', 'Catalyseur', 'Palier 1', 'Commun'],
    obtain:   "Obtenable par les Marchands d'Équipement"
  },
  {
    id:       'épée_en_fer',
    name:     "Épée en Fer",
    rarity:   'commun',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/epee_en_fer.png",
    lore:     "Épée en fer créée grâce aux loups de la vallée et avec un autre ingrédient.",
    tags:     ['Arme', 'Épée', 'Palier 1', 'Commun'],
    obtain:   "Fabricable au Forgeron d'Armes de la Ville de Départ"
  },
  {
    id:       'bouclier_dika',
    name:     "Bouclier d'Ika",
    rarity:   'commun',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/bouclier_dika.png",
    lore:     "Forgé dans la carapace des tortues d'Ika. Idéal pour encaisser sans broncher.",
    tags:     ['Arme', 'Bouclier', 'Pavois', 'Palier 1', 'Commun'],
    obtain:   "Fabricable au Forgeron d'Armes de la Ville de Départ"
  },
  {
    id:       'bouclier_pointu_en_bois',
    name:     "Bouclier Pointu en Bois",
    rarity:   'commun',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/bouclier_pointu_en_bois.png",
    lore:     "Ce bouclier fait de bois possède une pointe en son centre. Il peut encaisser quelques coups aussi.",
    tags:     ['Arme', 'Bouclier', 'Rondache', 'Palier 1', 'Commun'],
    obtain:   "Fabricable au Forgeron d'Armes de la Ville de Départ"
  },
  {
    id:       'dague_intermediaire',
    name:     "Dague Intermédiaire",
    rarity:   'commun',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/dague_intermediaire.png",
    lore:     "Standard des nouvelles recrues. Facile à manier, légère et très fiable.",
    tags:     ['Arme', 'Dague', 'Palier 1', 'Commun'],
    obtain:   "Fabricable au Forgeron d'Armes de la Ville de Départ"
  },
  {
    id:       'hache_double_en_fer',
    name:     "Hache Double en Fer",
    rarity:   'commun',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/hache_double_en_fer.png",
    lore:     "Double hache en fer créée grâce aux loups de la vallée et avec un autre ingrédient.",
    tags:     ['Arme', 'Hache', 'Palier 1', 'Commun'],
    obtain:   "Fabricable au Forgeron d'Armes de la Ville de Départ"
  },
  {
    id:       'viande_de_sanglier',
    name:     "Viande de Sanglier",
    rarity:   'commun',
    category: 'nourriture',
    palier:   1,
    image:    "../img/compendium/textures/items/viande_de_sanglier.png",
    lore:     "Cette belle viande de sanglier, bien juteuse, peut vous donner encore plus envie de manger !",
    tags:     ['Nourriture', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Sangliers Corrompus\n- Pumba"
  },
  {
    id:       'peau_de_sanglier',
    name:     "Peau de Sanglier",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/peau_de_sanglier.png",
    lore:     "Utilisable pour de la tannerie basique.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Sangliers Corrompus\n- Pumba"
  },
  {
    id:       'cristal_corrompu',
    name:     "Cristal Corrompu",
    rarity:   'commun',
    category: 'quete',
    palier:   1,
    image:    "../img/compendium/textures/items/cristal_corrompu.png",
    lore:     "Des traces de corruptions émanent de cet objet.",
    tags:     ['Quête', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Sangliers Corrompus\n- Pumba"
  },
  {
    id:       'anneau_de_pumba',
    name:     "Anneau de Pumba",
    rarity:   'legendaire',
    category: 'accessoire',
    palier:   1,
    image:    "../img/compendium/textures/trinkets/P1/Anneau\ de\ Pumba.png",
    lore:     "Taillé dans un métal épais et marqué par une rayure rouge, cet anneau est inspiré du célèbre sanglier massif.",
    tags:     ['Accessoire', 'Anneau', 'Palier 1', 'Légendaire'],
    obtain:   "Obtenable en tuant:\n- Pumba"
  },
  {
    id:       'fourrure_de_loup',
    name:     "Fourrure de Loup",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/fourrure_de_loup.png",
    lore:     "Une fourrure souple et légère, utilisée pour fabriquer des armures.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Loups Sinistre (Blancs & Noirs)\n- Albal"
  },
  {
    id:       'crocs_de_loup',
    name:     "Crocs de Loup",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/crocs_de_loup.png",
    lore:     "Une dent longue et acérée, prisée de certains artisans.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Loups Sinistre (Blancs & Noirs)\n- Albal"
  },
  {
    id:       'crocs_de_albal',
    name:     "Crocs de Albal",
    rarity:   'rare',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/crocs_de_albal.gif",
    lore:     "Un croc massif imprégné de sa rage sauvage. Son essence est utilisée pour concoter des potions de force redoutable.",
    tags:     ['Matériaux', 'Palier 1', 'Rare'],
    obtain:   "Obtenable en tuant:\n- Albal"
  },
  {
    id:       'spore_corrompu',
    name:     "Spore Corrompu",
    rarity:   'commun',
    category: 'quete',
    palier:   1,
    image:    "../img/compendium/textures/items/spore_corrompu.png",
    lore:     "Un spore étrange imprégné de corruption...",
    tags:     ['Quête', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Nephentes"
  },
  {
    id:       'fragment_de_feuille',
    name:     "Fragment de Feuille",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/fragment_de_feuille.png",
    lore:     "Des restes végétaux porteurs d'une étrange énergie naturelle.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Nephentes"
  },
  {
    id:       'pousse_de_sylve',
    name:     "Pousse de Sylve",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/pousse_de_sylve.png",
    lore:     "Petite pousse dans un bol très utile dans la confection de potion de vie.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Minis Tréants"
  },
  {
    id:       'éclat_de_bois_magique',
    name:     "Éclat de Bois Magique",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/eclat_de_bois_magique.png",
    lore:     "Fragment d'un ancien Tréant. Même détaché de celui-ci il conserve encore de la magie à l'intérieur.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Minis Tréants"
  },
  {
    id:       'écorce_de_titan',
    name:     "Écorce de Titan",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/ecorce_de_titan.png",
    lore:     "Ressource très dure presque incassable, les Guerriers pourront se protéger avec.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Guerriers Tréants"
  },
  {
    id:       'racine_ancestrale',
    name:     "Racine Ancestrale",
    rarity:   'rare',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "Un loot assez rare du Guerrier Tréant. Utile si vous avez besoin de fabriquer des potions.",
    tags:     ['Matériaux', 'Palier 1', 'Rare'],
    obtain:   "Obtenable en tuant:\n- Guerriers Tréants"
  },
  {
    id:       'bouclier_sylvestre',
    name:     "Bouclier Sylvestre",
    rarity:   'rare',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/bouclier_sylvestre.png",
    lore:     "Grand bouclier en bois qui peut seulement être obtenu par un Guerrier Tréant.",
    tags:     ['Arme', 'Bouclier', 'Pavois', 'Palier 1', 'Rare'],
    obtain:   "Obtenable en tuant:\n- Guerriers Tréants"
  },
  {
    id:       'écorce_sylvestre',
    name:     "Écorce Sylvestre",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "Matériau de la nature, utilisé principalement pour des armures légères et rapides.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Tréants d'Élites"
  },
  {
    id:       'corde_darc_sylvestre',
    name:     "Corde d'Arc Sylvestre",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/corde_darc_sylvestre.png",
    lore:     "Longue et tendue, cette corde robuste est idéale pour confectionner un nouvel arc.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Tréants d'Élites"
  },
  {
    id:       'arc_sylvestre',
    name:     "Arc Sylvestre",
    rarity:   'commun',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/arc_sylvestre.png",
    lore:     "Arc construitavec l'aidees Tréants du Palier 1 de l'Aincrad.",
    tags:     ['Arme', 'Arc', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Tréants d'Élites\nFabricable au Forgeron d'Armes de la Ville de Départ"
  },
  {
    id:       'brindille_enchantée',
    name:     "Brindille Enchantée",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/brindille_enchantee.png",
    lore:     "Brindille du Mage Sylvestre, ce bâton peutêtre utilisé comme basepour une arme magique.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Mages Sylvestres"
  },
  {
    id:       'coeur_de_bois',
    name:     "Cœur de Bois",
    rarity:   'rare',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/coeur_de_bois.png",
    lore:     "Cœur imprégné de magie, si vous l'utilisez avec précaution une arme très redoutable peut être créée.",
    tags:     ['Matériaux', 'Palier 1', 'Rare'],
    obtain:   "Obtenable en tuant:\n- Mages Sylvestres"
  },
  {
    id:       'tissu_spectral',
    name:     "Tissu Spectral",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/tissu_spectral.png",
    lore:     "Un tissu imprégné de magie noire et de malédictions.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Mages Sylvestres"
  },
  {
    id:       'bâton_sylvestre',
    name:     "Bâton Sylvestre",
    rarity:   'commun',
    category: 'arme',
    palier:   1,
    images:    ["../img/compendium/textures/weapons/baton_sylvestre_mage.png", "../img/compendium/textures/weapons/baton_sylvestre_shaman.png"],
    lore:     "Un livre forgé par des matériaux venant d'un marécage putride et ancien. Il renferme une magie élémentaire.",
    tags:     ['Arme', 'Catalyseur', 'Palier 1', 'Commun'],
    obtain:   "Fabricable au Forgeron d'Armes de la Ville de Départ"
  },
  {
    id:       'grimoire_sylvestre',
    name:     "Grimoire Sylvestre",
    rarity:   'commun',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/grimoire_sylvestre.png",
    lore:     "Un livre forgé par des matériaux venant d'un marécage putride et ancien. Il renferme une magie élémentaire.",
    tags:     ['Arme', 'Catalyseur', 'Palier 1', 'Commun'],
    obtain:   "Fabricable au Forgeron d'Armes de la Ville de Départ"
  },
  {
    id:       'grimoire_bestial',
    name:     "Grimoire Bestial",
    rarity:   'commun',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/grimoire_bestial.png",
    lore:     "Un livre forgé par des matériaux venant d'un marécage putride et ancien. Il renferme une magie bestiale.",
    tags:     ['Arme', 'Catalyseur', 'Palier 1', 'Commun'],
    obtain:   "Fabricable au Forgeron d'Armes de la Ville de Départ"
  },
  {
    id:       'mycelium_magique',
    name:     "Mycélium Magique",
    rarity:   'rare',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/mycelium_magique.png",
    lore:     "Ingrédient assez rare pour de la haute alchimie ou pour autre chose ?",
    tags:     ['Matériaux', 'Palier 1', 'Rare'],
    obtain:   "Obtenable en tuant:\n- Gardiens Colossaux"
  },
  {
    id:       'marteau_du_colosse',
    name:     "Marteau du Colosse",
    rarity:   'rare',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/marteau_du_colosse.png",
    lore:     "Arme de destruction du Gardien Colossal. Ce marteau est puissant mais lourd.",
    tags:     ['Arme', 'Marteau', 'Palier 1', 'Rare'],
    obtain:   "Obtenable en tuant:\n- Gardiens Colossaux"
  },
  {
    id:       'gelée_de_slime',
    name:     "Gelée de Slime",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "Une petite et belle gelée gluante qui colle à vos mains pendant longtemps.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Petits Slimes\n- Guerriers Slimes\n- Slimes Soigneurs\n- Slimes Magiciens\n- Gorbel"
  },
  {
    id:       'noyau_de_slime',
    name:     "Noyau de Slime",
    rarity:   'rare',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/noyau_de_slime.png",
    lore:     "Noyau imprégné de la magie des slimes. Utilisé dasn la confection d'accessoires magiques.",
    tags:     ['Matériaux', 'Palier 1', 'Rare'],
    obtain:   "Obtenable en tuant:\n- Slimes Soigneurs\n- Slimes Magiciens\n- Gorbel"
  },
  {
    id:       'essence_de_gorbel',
    name:     "Essence de Gorbel",
    rarity:   'epique',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/essence_de_gorbel.png",
    lore:     "Essence d'un slime qui a atteint son plus haut potentiel.",
    tags:     ['Matériaux', 'Palier 1', 'Épique'],
    obtain:   "Obtenable en tuant:\n- Gorbel"
  },
  {
    id:       'os_de_squelette',
    name:     "Os de Squelette",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/os_de_squelette.png",
    lore:     "Petit os que l'on trouve sur des squelettes de bas rang. Sûrement utile pour certaines confections.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Squelettes Épéiste\n- Guerriers Squelettes\n- Squelettes Hallebardiers\n- Squelettes Mages"
  },
  {
    id:       'poussière_dos',
    name:     "Poussière d'Os",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "Résidu d'os réduit en poudre. Sert de catalyseur pour des potions de vie.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Squelettes Épéiste\n- Guerriers Squelettes\n- Squelettes Hallebardiers\n- Archers Squelettes\n- Tanks Squelettes\n- Squelettes Mages"
  },
  {
    id:       'os_de_squelette_renforcé',
    name:     "Os de Squelette Renforcé",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "Contrairement au petit os, ces os sont plus résistants et sûrement utiles aussi dans certaines confections.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Squelettes Hallebardiers\n- Archers Squelettes\n- Tanks Squelettes"
  },
  {
    id:       'ames_des_ruines',
    name:     "Âmes des Ruines",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/ames_des_ruines.png",
    lore:     "Âme de squelette abreuvé de corruption.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Squelettes Épéiste\n- Guerriers Squelettes\n- Squelettes Hallebardiers\n- Archers Squelettes"
  },
  {
    id:       'épée_osseuse',
    name:     "Épée Osseuse",
    rarity:   'rare',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/epee_osseuse.png",
    lore:     "Taillé dans les os d'un ancien guerrier tombé en disgrâce.",
    tags:     ['Armes', 'Épée', 'Palier 1', 'Rare'],
    obtain:   "Obtenable en tuant:\n- Squelettes Épéiste\n- Guerriers Squelettes"
  },
  {
    id:       'tissu_maudit',
    name:     "Tissu Maudit",
    rarity:   'commun',
    category: 'quete',
    palier:   1,
    image:    "../img/compendium/textures/items/tissu_maudit.png",
    lore:     "Les forces obscures devorent ce tissu.",
    tags:     ['Quête', 'Palier 1', 'commun'],
    obtain:   "Obtenable en tuant:\n- Squelettes Épéiste\n- Guerriers Squelettes"
  },
  {
    id:       'bâton_de_squelette',
    name:     "Bâton de Squelette",
    rarity:   'rare',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/baton_squelettique.png",
    lore:     "Bâton ancien des ruines maudites, encore vivant de la flamme des morts.",
    tags:     ['Armes', 'Bâton', 'Palier 1', 'Rare'],
    obtain:   "Obtenable en tuant:\n- Squelettes Mages"
  },
  {
    id:       'coeur_putréfié',
    name:     "Cœur Putréfié",
    rarity:   'commun',
    category: 'quete',
    palier:   1,
    image:    "../img/compendium/textures/items/coeur_putrefie.png",
    lore:     "La putréfaction ronge peu à peu ce cœur.",
    tags:     ['Quête', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Narax Squelette Maudit"
  },
  {
    id:       'bâton_de_squelette_maudit',
    name:     "Bâton de Squelette Maudit",
    rarity:   'rare',
    category: 'arme',
    palier:   1,
    images:    ["../img/compendium/textures/weapons/baton_de_squelette_maudit_mage.png", "../img/compendium/textures/weapons/baton_de_squelette_maudit_shaman.png"],
    lore:     "Bâton encore imprégné de sa magie après la mort de son propriétaire.",
    tags:     ['Armes', 'Bâton', 'Palier 1', 'Rare'],
    obtain:   "Obtenable en tuant:\n- Narax Squelette Maudit"
  },
  {
    id:       'morceau_de_crinière_spectrale',
    name:     "Morceau de Crinière Spectrale",
    rarity:   'legendaire',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/morceau_de_criniere_spectrale.png",
    lore:     "Une mèche de crinière éthérée, arrachée a une monture spectrale. Elle palpite encore d'une énergie rapide.",
    tags:     ['Matériaux', 'Palier 1', 'Legendaire'],
    obtain:   "Obtenable en tuant:\n- Nasgul"
  },
  {
    id:       'éclat_du_sabot_maudit',
    name:     "Éclat du Sabot Maudit",
    rarity:   'legendaire',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/eclat_du_sabot_maudit.png",
    lore:     "Fragment arraché au sabot d'une créature maudite. Il renferme une énergie sombre qui confère à son porteur une vitesse surnaturelle.",
    tags:     ['Matériaux', 'Palier 1', 'Legendaire'],
    obtain:   "Obtenable en tuant:\n- Nasgul"
  },
  {
    id:       'cuir_usé',
    name:     "Cuir Usé",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    "../img/compendium/textures/items/cuir_use.png",
    lore:     "Un morceau de cuir abîmé autrefois portépar des Bandits. Il reste utilisable.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Bandits Archer\n- Bandits Assassins\n- Bandits Robustes"
  },
  {
    id:       'petite_bourse',
    name:     "Petite Bourse",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "Un petit sac en tissu, parfait pour y glisser des pièces.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Bandits Archer\n- Bandits Assassins\n- Bandits Robustes"
  },
  {
    id:       'arbalète_de_bandit',
    name:     "Arbalète de Bandit",
    rarity:   'rare',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/arbalete_de_bandit.png",
    lore:     "Arbalète d'un bandit qui devient presque inutilisable après tous ces combats.",
    tags:     ['Armes', 'Arbalète', 'Palier 1', 'Rare'],
    obtain:   "Obtenable en tuant:\n- Bandits Archer"
  },
  {
    id:       'dague_de_bandit',
    name:     "Dague de Bandit",
    rarity:   'rare',
    category: 'arme',
    palier:   1,
    image:    "../img/compendium/textures/weapons/dague_de_bandit.png",
    lore:     "Dague émoussé d'un bandit après tous ces combats sanglants.",
    tags:     ['Armes', 'Dague', 'Palier 1', 'Rare'],
    obtain:   "Obtenable en tuant:\n- Bandits Assassins"
  },
  {
    id:       'carapace_dika',
    name:     "Carapace de d'Ika",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "Un morceau épais de carapace issu d'une tortue d'Ika abattue.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Ika"
  },
  {
    id:       'pièce_métal_enchanté',
    name:     "Pièce de Métal Enchanté",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "Petite ferraille de métal, avec d'autres ingrédients il est possible d'en faire des Lingôts de Métal Enchanté.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Soldat Déchu\n- Guerrier Déchu"
  },
  {
    id:       'pièce_âme_métal',
    name:     "Pièce d'Âme de Métal",
    rarity:   'rare',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "Petite ferraille de métal, avec d'autres ingrédients il est possible d'en faire des Lingôts d'Âme de Métal.",
    tags:     ['Matériaux', 'Palier 1', 'rare'],
    obtain:   "Obtenable en tuant: Guerrier Déchu"
  },
  {
    id:       'artefact_fallen',
    name:     "Artéfact des Fallen",
    rarity:   null,
    category: 'quete',
    palier:   1,
    image:    null,
    lore:     null,
    tags:     ['Objets de Quête', 'Palier 1', null],
    obtain:   "Obtenable en tuant:\n- Gardien Déchu\n- Héraut Déchu\n- Faucheuse Déchu"
  },
  {
    id:       'âme_warden',
    name:     "Âme du Warden",
    rarity:   'rare',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "Une âme est contenue dans cet objet. Il peut être obtenu en tuant son possesseur ou en le fabriquant au forgeron.",
    tags:     ['Matériaux', 'Palier 1', 'rare'],
    obtain:   "Obtenable en tuant: Gardien Déchu"
  },
  {
    id:       'âme_herald',
    name:     "Âme de l'Herald",
    rarity:   'rare',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "Une âme est contenue dans cet objet. Il peut être obtenu en tuant son possesseur ou en le fabriquant au forgeron.",
    tags:     ['Matériaux', 'Palier 1', 'rare'],
    obtain:   "Obtenable en tuant: Héraut Déchu"
  },
  {
    id:       'âme_reaper',
    name:     "Âme du Reaper",
    rarity:   'rare',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "Une âme est contenue dans cet objet. Il peut être obtenu en tuant son possesseur ou en le fabriquant au forgeron.",
    tags:     ['Matériaux', 'Palier 1', 'rare'],
    obtain:   "Obtenable en tuant: Faucheuse Déchue"
  },
  {
    id:       'anneau_faucheuse',
    name:     "Anneau de la Faucheuse",
    rarity:   "Légendaire",
    category: 'accessoire',
    palier:   1,
    image:    null,
    lore:     "Anneau qui appartenait à la faucheuse. À son départ il est tombé par terre, encore imprégné de sa grande magie.",
    tags:     ['Accessoires', 'Palier 1', "Légendaire"],
    obtain:   "Obtenable en tuant : Faucheuse Déchue"
  },
  {
    id:       'bouclier_oublié',
    name:     "Bouclier Oublié",
    rarity:   "Légendaire",
    category: 'arme',
    palier:   1,
    image:    null,
    lore:     null,
    tags:     ['Armes', 'Palier 1', "Légendaire"],
    obtain:   "Obtenable en tuant : Ornstein, Dévastateur Déchu"
  },
  {
    id:       'hallebarde_royale',
    name:     "Hallebarde Royale",
    rarity:   "Légendaire",
    category: 'arme',
    palier:   1,
    image:    null,
    lore:     "Hallebarde d'un seigneur déchu anciennement grand guerrier dans l'Aincrad et dans tout The Seed",
    tags:     ['Armes', 'Palier 1', "Légendaire"],
    obtain:   "Obtenable en tuant : Smough, Dévastateur Déchu"
  },
  {
    id:       'tissu_araignée',
    name:     "Tissu d'Araignée",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "Un tissu fin, mais incroyablement résistant. Idéal pour des équipements légers ou enchantés.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant : Araignée des Forêts"
  },
  {
    id:       'fil_araignée',
    name:     "Fil d'Araignée",
    rarity:   'rare',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "Petit fil très fragile il peut se casser à tout moment.",
    tags:     ['Matériaux', 'Palier 1', 'rare'],
    obtain:   "Obtenable en tuant : Araignée des Forêts"
  },
  {
    id:       'peau_cerf_montagnes',
    name:     "Peau de Cerf des Montagnes",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "Un morceau de peau épaisse, rigide, utile pour des armures robustes.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant : Cerf des Montagnes"
  },
  {
    id:       'peau_dur_glacial',
    name:     "Peau Dur Glacial",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "Une plaque de givre solidifiée, aussi dur que de la pierre.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant : Golem de Glace"
  },
  {
    id:       'poussière_givre',
    name:     "Poussière de Givre",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "Une fine poudre glaciale récoltée sur des créatures de glace.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant:\n- Golem de Glace\n- Spirite de Glace\n- Ours de Glace"
  },
  {
    id:       'éclat_magique_glacial',
    name:     "Éclat Magique Glacial",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "Un fragment cristallin baigné de magie ancienne. Il est prisé pour forger des armures mystiques.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant : Spirite de Glace"
  },
  {
    id:       'fragment_âme_ours',
    name:     "Fragment de l'Âme de l'Ours",
    rarity:   'rare',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "L'âme de l'Ours repose dans ce fragment. Utilisez-le avec sagesse, car son pouvoir est colossal.",
    tags:     ['Matériaux', 'Palier 1', 'rare'],
    obtain:   "Obtenable en tuant : Ours de Glace"
  },
  {
    id:       'carapace_requin',
    name:     "Carapace de Requin",
    rarity:   'commun',
    category: 'materiaux',
    palier:   1,
    image:    null,
    lore:     "Une plaque de carapace très dure, arrachée à un poisson-requin. Solide et résistante parfaite pour une certaine armure lourdre.",
    tags:     ['Matériaux', 'Palier 1', 'Commun'],
    obtain:   "Obtenable en tuant : Poisson Requin"
  },
  {
    id:       'cœur_nymbréa',
    name:     "Cœur de Nymbréa",
    rarity:   'rare',
    category: 'quete',
    palier:   1,
    image:    null,
    lore:     "Encore brûlant et chargé de magie aquatique, ce cœur scintille d'une énergie ancienne.",
    tags:     ['Matériaux', 'Palier 1', 'rare'],
    obtain:   "Obtenable en tuant : Nymbréa"
  },
  {
    id:       'peau_épaisse',
    name:     "Peau Épaisse",
    rarity:   'rare',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Une peau robuste et résistante, capable d'absorber de lourds impacts.",
    tags:     ['Matériaux', 'Palier 2', 'rare'],
    obtain:   "Obtenable en tuant : Taureau Monstrueux"
  },
  {
    id:       'corne_taureau',
    name:     "Corne de Taureau",
    rarity:   'rare',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Solide et acérée, cette corne témoigne de la force brutale de l'animal.",
    tags:     ['Matériaux', 'Palier 2', 'rare'],
    obtain:   "Obtenable en tuant : Taureau"
  },
  {
    id:       'peau_ours',
    name:     "Peau d'Ours",
    rarity:   'commun',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Une épaisse fourrure tannée, capable de résister aux assauts et d'offrir une chaleur inégalée.",
    tags:     ['Matériaux', 'Palier 2', 'commun'],
    obtain:   "Obtenable en tuant : Ours de la Forêt"
  },
  {
    id:       'griffe_ours',
    name:     "Griffe d'Ours",
    rarity:   'commun',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Tranchante et recourbée, elle témoigne de la férocité et de la force d'un prédateur redoutable.",
    tags:     ['Matériaux', 'Palier 2','commun'],
    obtain:   "Obtenable en tuant : Ours de la Forêt"
  },
  {
    id:       'graisse_ours',
    name:     "Graisse d'Ours",
    rarity:   'rare',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Utilisée pour l'entretien du cuir ou comme combustible, cette graisse dégage une forte odeur sauvage.",
    tags:     ['Matériaux', 'Palier 2', 'rare'],
    obtain:   "Obtenable en tuant : Ours de la Forêt"
  },
  {
    id:       'résidu_miel',
    name:     "Résidu de Miel",
    rarity:   'commun',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Restes collants et sucrés, souvent imprégnés de pollen et de senteurs florales.",
    tags:     ['Matériaux', 'Palier 2', 'commun'],
    obtain:   "Obtenable en tuant : Ours de la Forêt"
  },
  {
    id:       'fourrure_loup',
    name:     "Fourrure de Loup",
    rarity:   'commun',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Chaud et souple, ce pelage protège efficacement du froid. Parfait pour créer des armures légères.",
    tags:     ['Matériaux', 'Palier 2', 'commun'],
    obtain:   "Obtenable en tuant:\n- Loups des Montagnes\n- Loups des Savanes"
  },
  {
    id:       'dard',
    name:     "Dard",
    rarity:   'rare',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Pointu et redoutable, ce dard d'abeille géante est un matériau de choix pour fabriquer des équipements perforants.",
    tags:     ['Matériaux', 'Palier 2', 'rare'],
    obtain:   "Obtenable en tuant:\n- Ouvrière\n- Dardroyal\n- Melisara, Souveraine de la Ruche"
  },
  {
    id:       'miel',
    name:     "Miel",
    rarity:   'rare',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Doux mais étonnement visqueux, ce miel concentré est utilisé pour enduire certaines armures.",
    tags:     ['Matériaux', 'Palier 2', 'rare'],
    obtain:   "Obtenable en tuant:\n- Ouvrière\n- Melisara, Souveraine de la Ruche"
  },
  {
    id:       'carapace_abeille',
    name:     "Carapace d'Abeille",
    rarity:   'rare',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Épaisse et segmentée, cette carapace protège efficacement contre les assauts. Parfaite pour façonner des équipements.",
    tags:     ['Matériaux', 'Palier 2', 'rare'],
    obtain:   "Obtenable en tuant:\n- Dardroyal\n- Melisara, Souveraine de la Ruche"
  },
  {
    id:       'plume_enflammée',
    name:     "Plume Enflammée",
    rarity:   'commun',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Une plume incandescente, vibrant d'énergie magique. Utilisée par les artisans.",
    tags:     ['Matériaux', 'Palier 2', 'commun'],
    obtain:   "Obtenable en tuant : Harpie de Feu"
  },
  {
    id:       'plume_flamboyante',
    name:     "Plume Flamboyante",
    rarity:   'rare',
    category: 'accessoire',
    palier:   2,
    image:    null,
    lore:     "Une plume rouge intense aux nuances ardentes, évoquant la chaleur d'une flamme vive.",
    tags:     ['Accessoires', 'Palier 2', 'rare'],
    obtain:   "Obtenable en tuant : Harpie de Feu"
  },
  {
    id:       'plume_terreuse',
    name:     "Plume Terreuse",
    rarity:   'commun',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Une plume dense et résistante, imprégnée de force tellurique parfaite.",
    tags:     ['Matériaux', 'Palier 2', 'commun'],
    obtain:   "Obtenable en tuant : Harpie de Terre"
  },
  {
    id:       'plume_écarlate',
    name:     "Plume Écarlate",
    rarity:   'rare',
    category: 'accessoire',
    palier:   2,
    image:    null,
    lore:     "Une plume d'un vert profond aux reflets vifs, légère et délicatement nervurée",
    tags:     ['Accessoires', 'Palier 2', 'rare'],
    obtain:   "Obtenable en tuant : Harpie de Terre"
  },
  {
    id:       'plume_ondoyante',
    name:     "Plume Ondoyante",
    rarity:   'commun',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Une plume souple et scintillante, gorgée d'essence aquatique.",
    tags:     ['Matériaux', 'Palier 2', 'commun'],
    obtain:   "Obtenable en tuant : Harpie de Foudre"
  },
  {
    id:       'œuf_harpie_eau',
    name:     "Œuf de Harpie d'Eau",
    rarity:   'commun',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Un œuf provenant d'une harpie... Cache-t-il peut-être un nouveau-né ?",
    tags:     ['Matériaux', 'Palier 2', 'commun'],
    obtain:   "Obtenable en tuant : Harpie de Foudre"
  },
  {
    id:       'plume_azur',
    name:     "Plume Azur",
    rarity:   'rare',
    category: 'accessoire',
    palier:   2,
    image:    null,
    lore:     "Une plume bleu aux éclats profond, semblant capturer la teinte du ciel",
    tags:     ['Accessoires', 'Palier 2', 'rare'],
    obtain:   "Obtenable en tuant : Harpie de Foudre"
  },
  {
    id:       'écaille_fulgurante',
    name:     "Écaille Fulgurante",
    rarity:   'rare',
    category: 'quete',
    palier:   2,
    image:    null,
    lore:     "Une des trois écorces utilisées comme offrande à l'un des dieux présents au Palier 2 !",
    tags:     ['Matériaux', 'Palier 2', 'rare'],
    obtain:   "Obtenable en tuant : Poisson Fulgurant"
  },
  {
    id:       'pierre_runique',
    name:     "Pierre Runique",
    rarity:   'commun',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Gravée d'inscriptions anciennes, elle ne s'active qu'en présence d'un second composant.",
    tags:     ['Matériaux', 'Palier 2', 'commun'],
    obtain:   "Obtenable en tuant:\n- Squelette du Sanctuaire - Archer\n- Squelette du Sanctuaire - Shaman\n- Squelette du Sanctuaire - Guerrier\n- Gardien du Sanctuaire"
  },
  {
    id:       'chaîne_spectrale',
    name:     "Chaîne Spectrale",
    rarity:   'commun',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Gravée d'inscriptions anciennes, elle ne s'active qu'en présence d'un second composant.",
    tags:     ['Matériaux', 'Palier 2', 'commun'],
    obtain:   "Obtenable en tuant:\n- Squelette du Sanctuaire - Archer\n- Squelette du Sanctuaire - Shaman\n- Squelette du Sanctuaire - Guerrier"
  },
  {
    id:       'vêtement_déchiré',
    name:     "Vêtement Déchiré",
    rarity:   'rare',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Un vêtement déchiré appartenant à un ancien humain, devenu squelette protégeant son domaine.",
    tags:     ['Matériaux', 'Palier 2', 'rare'],
    obtain:   "Obtenable en tuant:\n- Squelette du Sanctuaire - Archer\n- Squelette du Sanctuaire - Guerrier"
  },
  {
    id:       'poudre_moelle',
    name:     "Poudre de Moelle",
    rarity:   'rare',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Une belle poudre blanchâtre à l'odeur minérale, possiblement utilisé dans certains rituels.",
    tags:     ['Matériaux', 'Palier 2', 'rare'],
    obtain:   "Obtenable en tuant : Squelette du Sanctuaire - Shaman"
  },
  {
    id:       'collier_runique',
    name:     "Collier Runique",
    rarity:   'epique',
    category: 'accessoire',
    palier:   2,
    image:    null,
    lore:     "Collier fabriqué par d'ancien matériaux poussiéreux, mais drôlement résistant.",
    tags:     ['Accessoires', 'Palier 2', 'Épique'],
    obtain:   "Obtenable en tuant : Gardien du Sanctuaire"
  },
  {
    id:       'morceau_ferraille',
    name:     "Morceau de Ferraille",
    rarity:   'rare',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Morceau de feraille, solide malgré son état. Idéal pour expérimenter la forge ou tester des recettes alchimiques.",
    tags:     ['Matériaux', 'Palier 2', 'rare'],
    obtain:   "Obtenable en tuant : Golem de Pierre"
  },
  {
    id:       'pierre_osseuse_noire',
    name:     "Pierre Osseuse Noire",
    rarity:   'rare',
    category: 'materiaux',
    palier:   2,
    image:    null,
    lore:     "Un fragment d'os dur et sombre, marqué par le temps et par la mort.",
    tags:     ['Matériaux', 'Palier 2', 'rare'],
    obtain:   "Obtenable en tuant:\n- ??\n- Morveth l'Écorcheur d'Âmes"
  },

];