const FLOOR_COUNT = 100;

const MARKER_EMOJI = {
  région:           '📍',
  zone_monstre:     '💀',
  quête_principale: '💬',
  quête_secondaire: '❓',
  repreneur_butin:  '🛒',
  marchand:         '💰',
  artisant:         '⚒️',
  clef:             '🗝️',
  ressource:        '🌿',
  donjon:           '⚔️',
};

const FLOOR_NAMES = {
  1: 'Forêt',
  2: 'Désert',
};

const FLOOR_ZONES = {
  1: [
    {
      id: 'z1',
      name: 'Vallée des Loups',
      regionName: 'Vallée des Loups',
      color: '#e0ac60',
      emoji: '🐺',
      monsters: [
        { name: 'Loup Sinitre Blanc', level: 2, difficulty: '⭐',   emoji: '🐺', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/vallee-des-loups/loups-sinistres' },
        { name: 'Loup Sinitre Noir',  level: 2, difficulty: '⭐',   emoji: '🐺', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/vallee-des-loups/loups-sinistres' },
        { name: 'Albal',              level: 2, difficulty: '⭐⭐', emoji: '🐺', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/vallee-des-loups/albal' },
      ],
      points: [
        { gx: 2356, gy: 4026 }, { gx: 2270, gy: 3943 }, { gx: 2306, gy: 3784 },
        { gx: 2400, gy: 3651 }, { gx: 2583, gy: 3667 }, { gx: 2628, gy: 3849 },
        { gx: 2571, gy: 3982 },
      ],
    },
    {
      id: 'z2',
      name: 'Zone des Sangliers',
      regionName: 'Zone des Sangliers',
      color: '#644d58',
      emoji: '🐗',
      monsters: [
        { name: 'Sanglier Corrompu', level: 2, difficulty: '⭐',   emoji: '🐗', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/zone-sanglier/sanglier-corrompu' },
        { name: 'Pumba',             level: 2, difficulty: '⭐⭐', emoji: '🐗', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/zone-sanglier/pumba' },
      ],
      points: [
        { gx: 1537, gy: 3620 }, { gx: 1707, gy: 3344 }, { gx: 1912, gy: 3339 },
        { gx: 2060, gy: 3470 }, { gx: 2057, gy: 3713 }, { gx: 1783, gy: 3619 },
      ],
    },
    {
      id: 'z3',
      name: 'Champs de Mizunari',
      color: '#82e753',
      emoji: '🌾',
      monsters: [
        { name: 'Nephentes', level: 4, difficulty: '⭐⭐', emoji: '🥬', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/mizunari/nephentes' },
      ],
      points: [
        { gx: 3232, gy: 3731 }, { gx: 3286, gy: 3708 }, { gx: 3349, gy: 3771 },
        { gx: 3292, gy: 3828 }, { gx: 3252, gy: 3786 },
      ],
    },
    {
      id: 'z4',
      name: 'Marécage Putride',
      regionName: 'Marécage Putride',
      color: '#ee7560',
      emoji: '🍄',
      monsters: [
        { name: 'Mini Tréant',       level: 3, difficulty: '⭐⭐',   emoji: '🌿', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/hanaka/mini-treant' },
        { name: 'Guerrier Tréant',   level: 3, difficulty: '⭐⭐',   emoji: '🛡️', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/hanaka/guerrier-treant' },
        { name: "Tréant d'Élite",    level: 3, difficulty: '⭐⭐',   emoji: '🏹', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/hanaka/treant-elite' },
        { name: 'Mage Sylvestre',    level: 3, difficulty: '⭐⭐',   emoji: '🧙', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/hanaka/mage-sylvestre' },
        { name: 'Gardien Colossal',  level: 3, difficulty: '⭐⭐⭐', emoji: '🌳', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/hanaka/gardien-colossal' },
      ],
      points: [
        { gx: 1589, gy: 3261 }, { gx: 1432, gy: 3269 }, { gx: 989, gy: 3272 },
        { gx: 954, gy: 3146 },  { gx: 1003, gy: 2934 }, { gx: 1328, gy: 2938 },
        { gx: 1519, gy: 2831 }, { gx: 1668, gy: 3084 },
      ],
    },
    {
      id: 'z5',
      name: 'Vallhat',
      regionName: 'Vallhat',
      color: '#74ce50',
      emoji: '🌳',
      monsters: [
        { name: 'Petit Slime',      level: 3, difficulty: '⭐⭐',    emoji: '🟢', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/vallhat/petit-slime' },
        { name: 'Guerrier Slime',   level: 3, difficulty: '⭐⭐',    emoji: '⚔️', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/vallhat/guerrier-slime' },
        { name: 'Slime Soigneur',   level: 3, difficulty: '⭐⭐⭐',  emoji: '⛑️', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/vallhat/slime-soigneur' },
        { name: 'Slime Magicien',   level: 3, difficulty: '⭐⭐⭐',  emoji: '🧙', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/vallhat/slime-magicien' },
        { name: 'Gorbel',           level: 3, difficulty: '⭐⭐⭐⭐',emoji: '👑', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/vallhat/gorbel' },
      ],
      points: [
        { gx: 515, gy: 3184 }, { gx: 387, gy: 3378 }, { gx: 238, gy: 3398 },
        { gx: 129, gy: 3104 }, { gx: 90, gy: 2795 },   { gx: 266, gy: 2693 },
        { gx: 498, gy: 2796 }, { gx: 595, gy: 3025 },
      ],
    },
    {
      id: 'z6',
      name: 'Ruines Maudites',
      color: '#eecf21',
      emoji: '💀',
      monsters: [
        { name: 'Squelette Épéiste',      level: 3, difficulty: '⭐⭐',   emoji: '💀', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/ruines-maudites/squelette-epeiste' },
        { name: 'Guerrier Squelette',     level: 3, difficulty: '⭐⭐⭐', emoji: '⚔️', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/ruines-maudites/guerrier-squelette' },
        { name: 'Squelette Hallebardier', level: 3, difficulty: '⭐⭐⭐', emoji: '🔨', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/ruines-maudites/squelette-hallbardier' },
      ],
      points: [
        { gx: 2692, gy: 4371 }, { gx: 2757, gy: 4375 }, { gx: 2815, gy: 4427 },
        { gx: 2808, gy: 4497 }, { gx: 2693, gy: 4470 },
      ],
    },
    {
      id: 'z7',
      name: 'Mine de Geldorak',
      regionName: 'Mine de Geldorak',
      color: '#75bdcf',
      emoji: '⛰️',
      monsters: [
        { name: 'Bandit Archer',   level: 3, difficulty: '⭐⭐', emoji: '🏹', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/mine-de-geldorak/bandit-archer' },
        { name: 'Bandit Assassin', level: 3, difficulty: '⭐⭐', emoji: '🗡️', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/mine-de-geldorak/bandit-assassin' },
        { name: 'Bandit Robuste',  level: 3, difficulty: '⭐⭐', emoji: '💪', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/mine-de-geldorak/bandit-robuste' },
      ],
      points: [
        { gx: 3922, gy: 3824 }, { gx: 4081, gy: 3834 }, { gx: 4201, gy: 3880 },
        { gx: 4083, gy: 3985 }, { gx: 3994, gy: 4036 }, { gx: 3916, gy: 3971 },
        { gx: 3907, gy: 3887 },
      ],
    },
    {
      id: 'z8',
      name: "Archipel d'Ika",
      regionName: "Archipel d'Ika",
      color: '#3e9db4',
      emoji: '🏝️',
      monsters: [
        { name: 'Ika', level: 3, difficulty: '⭐⭐⭐', emoji: '🐢', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/archipel-dika/ika' },
      ],
      points: [
        { gx: 3130, gy: 4055 }, { gx: 3163, gy: 4008 }, { gx: 3243, gy: 4010 },
        { gx: 3320, gy: 4084 }, { gx: 3321, gy: 4143 }, { gx: 3268, gy: 4185 },
        { gx: 3142, gy: 4180 }, { gx: 3113, gy: 4084 },
      ],
    },
    {
      id: 'z9',
      name: "Arakh'Nol",
      regionName: "Arakh'Nol",
      color: '#8bbeca',
      emoji: '🕸️',
      monsters: [
        { name: 'Araignée des Forêts', level: 7, difficulty: '⭐⭐⭐⭐', emoji: '🕷️', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-nord/arakhnol/araignees-des-forets' },
      ],
      points: [
        { gx: 1394, gy: 1186 }, { gx: 1472, gy: 1451 }, { gx: 1358, gy: 1489 },
        { gx: 1332, gy: 1581 }, { gx: 1152, gy: 1701 }, { gx: 1029, gy: 1743 },
        { gx: 990, gy: 1710 },  { gx: 1096, gy: 1512 }, { gx: 1085, gy: 1395 },
        { gx: 1138, gy: 1309 }, { gx: 989, gy: 1207 },  { gx: 1032, gy: 1146 },
        { gx: 1247, gy: 1210 },
      ],
    },
    {
      id: 'z10',
      name: 'Montagnes de Tolbana',
      color: '#ddb04e',
      emoji: '🏔️',
      monsters: [
        { name: 'Cerf des Montagnes', level: 7, difficulty: '⭐⭐⭐', emoji: '🦌', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-nord/tolbana/cerf-des-montagnes' },
      ],
      points: [
        { gx: 3945, gy: 1203 }, { gx: 4027, gy: 1066 }, { gx: 4187, gy: 1082 },
        { gx: 4115, gy: 1196 }, { gx: 4119, gy: 1280 }, { gx: 3998, gy: 1261 },
      ],
    },
    {
      id: 'z11a',
      name: 'Citadelle des Neiges',
      regionName: 'Citadelle des Neiges',
      color: '#224ba5',
      emoji: '❄️',
      monsters: [
        { name: 'Golem de Glace',   level: 7, difficulty: '⭐⭐⭐',    emoji: '🧊', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-nord/citadelle-des-neiges/golem-de-glace' },
        { name: 'Spirite de Glace', level: 7, difficulty: '⭐⭐⭐',    emoji: '🦋', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-nord/citadelle-des-neiges/spirite-de-glace' },
        { name: 'Ours de Glace',    level: 7, difficulty: '⭐⭐⭐⭐⭐',emoji: '🐻', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-nord/citadelle-des-neiges/ours-de-glace' },
      ],
      points: [
        { gx: 3969, gy: 2013 }, { gx: 3967, gy: 2039 }, { gx: 3943, gy: 2048 },
        { gx: 3886, gy: 2045 }, { gx: 3886, gy: 2007 }, { gx: 3907, gy: 1998 },
        { gx: 3945, gy: 1999 },
      ],
    },
    {
      id: 'z11b',
      name: 'Lac de Virelune',
      regionName: 'Antre de Aepep',
      color: '#bde3f1',
      emoji: '🎣',
      monsters: [
        { name: 'Poisson Requin', level: 7, difficulty: '⭐⭐⭐',    emoji: '🦈', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-nord/virelune/poisson-requin' },
        { name: 'Nymbréa',        level: 7, difficulty: '⭐⭐⭐⭐⭐',emoji: '🐟', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-nord/virelune/nymbrea' },
      ],
      points: [
        { gx: 1399, gy: 2022 }, { gx: 1397, gy: 2105 }, { gx: 1336, gy: 2141 },
        { gx: 1270, gy: 2106 }, { gx: 1256, gy: 2042 }, { gx: 1316, gy: 1986 },
        { gx: 1369, gy: 1999 },
      ],
    },
    {
      id: 'z12',
      name: 'Prairie des Sangliers',
      color: '#644d58',
      emoji: '🐗',
      monsters: [
        { name: 'Sanglier Corrompu', level: 2, difficulty: '⭐', emoji: '🐗', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/zone-sanglier/sanglier-corrompu' },
      ],
      points: [
        { gx: 2610, gy: 2304 }, { gx: 2492, gy: 2220 }, { gx: 2521, gy: 2015 },
        { gx: 2739, gy: 2117 }, { gx: 2650, gy: 2259 },
      ],
    },
  ],
  2: [],
};

const FLOOR_MARKERS = {
  1: [
    { id: 'm1',  type: 'donjon',  gx: 3334, gy: 1038, name: "Raid Tour du Kobold",          desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/donjons/donjon-kokolb' },
    { id: 'm2',  type: 'donjon',  gx: 2709, gy: 4408, name: 'Sous-Donjon Nasgul',           desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/donjons/donjon-squelette' },
    { id: 'm3',  type: 'donjon',  gx: 4210, gy: 3895, name: 'Donjon Mine de Geldorak',      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/donjons/donjon-geldorak' },
    { id: 'm4',  type: 'donjon',  gx: 2300, gy: 2400, name: "Donjon Labyrinthe des Déchus", desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/donjons/donjon-labyrinthe-des-dechus' },
    { id: 'm5',  type: 'donjon',  gx: 955,  gy: 1212, name: "Donjon Xal'Zirith",            desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/donjons/donjon-xalzirith' },

    { id: 'm6',  type: 'région',  gx: 1737, gy: 4300, name: 'Ville de Départ',        desc: "La ville de départ est un havre paisible dans un monde virtuel encore inconnu. C'est ici que chaque aventure commence", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/ville-de-depart' },
    { id: 'm7',  type: 'région',  gx: 1395, gy: 3450, name: 'Hanaka',                 desc: "Un hameau boisé niché entre les collines où les sangliers rôdent à la lisière. Berceau des premiers affrontements", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/hanaka' },
    { id: 'm8',  type: 'région',  gx: 2450, gy: 3853, name: 'Vallée des Loups',       desc: "Un vallon brumeux où résonnent encore les hurlements.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/vallee-des-loups' },
    { id: 'm9',  type: 'région',  gx: 1213, gy: 3108, name: 'Marécage Putride',       desc: "Un marais dense et hostile, où la brume empoisonne l'air.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/marecage-putride' },
    { id: 'm10', type: 'région',  gx: 1800, gy: 3500, name: 'Zone des Sangliers',     desc: "Un territoire sauvage où les sangliers règnent.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/zone-sanglier' },
    { id: 'm11', type: 'région',  gx: 948,  gy: 4189, name: 'Vallée des Pétales',     desc: "Une vallée enchantée où les pétales dansent au vent.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/vallee-des-petales' },
    { id: 'm12', type: 'région',  gx: 2764, gy: 4680, name: 'Château Abandonné',      desc: "Les ruines d'un château oublié, rongé par le temps.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/chateau-abandonne' },
    { id: 'm13', type: 'région',  gx: 3054, gy: 3684, name: 'Mizunari',               desc: "Petit village paisible niché au bord d'un lac clair.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/mizunari' },
    { id: 'm14', type: 'région',  gx: 3221, gy: 4097, name: "Archipel d'Ika",         desc: "Un archipel tropical où les tortues géantes se rassemblent.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/archipel-dika' },
    { id: 'm15', type: 'région',  gx: 2249, gy: 3210, name: 'Quartier OG',            desc: "Le bastion de la Guilde OG, réputée et redoutée.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/quartier-og' },
    { id: 'm16', type: 'région',  gx: 935,  gy: 3580, name: 'Cyclorim',               desc: "Une arène antique taillée dans la roche rouge.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/cyclorim' },
    { id: 'm17', type: 'région',  gx: 3978, gy: 3909, name: 'Mine de Geldorak',       desc: "Creusée au coeur de la montagne.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/mine-de-geldorak' },
    { id: 'm18', type: 'région',  gx: 2778, gy: 2998, name: 'CastelBrume',            desc: "Perché au sommet d'une crête oubliée.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/castelbrume' },
    { id: 'm19', type: 'région',  gx: 390,  gy: 3041, name: 'Vallhat',                desc: "Perchée au sommet d'un massif venteux.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/vallhat' },
    { id: 'm20', type: 'région',  gx: 3937, gy: 2031, name: 'Citadelle des Neiges',   desc: "Autrefois bastion imprenable.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/citadelle-des-neiges' },
    { id: 'm21', type: 'région',  gx: 313,  gy: 2455, name: 'Jardin des Géants',      desc: "Un lieu oublié où la nature a repris ses droits.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/jardin-des-geants' },
    { id: 'm22', type: 'région',  gx: 2454, gy: 2840, name: 'Le Lac des Nénuphars',   desc: "Calme et mystère entourent ses eaux troubles...", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/le-lac-des-nenuphars' },
    { id: 'm23', type: 'région',  gx: 3212, gy: 1639, name: 'Tolbana',                desc: "Érigé à flanc de montagne.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/tolbana' },
    { id: 'm24', type: 'région',  gx: 1325, gy: 2068, name: 'Antre de Aepep',         desc: "Au cœur d'une caverne oubliée dort un serpent ancien.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/antre-de-aepep' },
    { id: 'm25', type: 'région',  gx: 1490, gy: 1982, name: 'Virelune',               desc: "Niché au bord d'un gouffre marin insondable.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/virelune' },
    { id: 'm26', type: 'région',  gx: 1852, gy: 735,  name: 'Candelia',               desc: "Blotti entre les pics abrupts.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/candelia' },
    { id: 'm27', type: 'région',  gx: 3334, gy: 1038, name: 'Tour du Kobold',         desc: "Une ancienne tour en ruine.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/tour-du-kobold' },
    { id: 'm28', type: 'région',  gx: 2343, gy: 1702, name: 'Mine de Pic de Cristal', desc: "Cette ancienne mine renferme des cristaux.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/mine-de-pic-de-cristal' },
    { id: 'm29', type: 'région',  gx: 2969, gy: 1217, name: 'Cristal de Tolbana',     desc: "Des cristaux luminescents aux propriétés mystérieuses.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/cristal-de-tolbana' },
    { id: 'm30', type: 'région',  gx: 1232, gy: 1400, name: "Arakh'Nol",              desc: "Dans les profondeurs d'Arakh'Nol, la lumière peine à percer.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/arakhnol' },
    { id: 'm31', type: 'région',  gx: 4676, gy: 2438, name: 'Guilde Marchande',       desc: "Le Quartier général de la Guilde des Marchands.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/guilde-marchande' },

    { id: 'm32',  type: 'ressource', emoji: '🌾', gx: 2263, gy: 3706, name: 'Allium',              desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/herboriste#alliums' },
    { id: 'm35',  type: 'ressource', emoji: '🌾', gx: 2288, gy: 3653, name: 'Blé',                 desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/herboriste#ble' },
    { id: 'm36',  type: 'ressource', emoji: '🌳', gx: 2846, gy: 3517, name: 'Chêne de Forêt',      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/bucheron#chene' },
    { id: 'm38',  type: 'ressource', emoji: '🌳', gx: 2357, gy: 4301, name: 'Chêne Proche',        desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/bucheron#chene' },
    { id: 'm39',  type: 'ressource', emoji: '🌳', gx: 1707, gy: 1207, name: 'Bouleau',             desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/bucheron#bouleau' },
    { id: 'm40',  type: 'ressource', emoji: '⛏️', gx: 2309, gy: 3509, name: 'Charbon Petite Cave', desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/mineur#charbon' },
    { id: 'm41',  type: 'ressource', emoji: '⛏️', gx: 2309, gy: 3509, name: 'Cuivre Petite Cave',  desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/mineur#cuivre' },
    { id: 'm42',  type: 'ressource', emoji: '⛏️', gx: 2309, gy: 3509, name: 'Fer Petite Cave',     desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/mineur#fer' },
    { id: 'm43',  type: 'ressource', emoji: '⛏️', gx: 903,  gy: 3448, name: 'Charbon Grande Cave', desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/mineur#charbon' },
    { id: 'm44',  type: 'ressource', emoji: '⛏️', gx: 903,  gy: 3448, name: 'Cuivre Grande Cave',  desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/mineur#cuivre' },
    { id: 'm45',  type: 'ressource', emoji: '⛏️', gx: 903,  gy: 3448, name: 'Fer Grande Cave',     desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/mineur#fer' },

    { id: 'm46',  type: 'artisant', gx: 1703, gy: 4125, name: "Forgeron d'Armes",                 desc: "Forgeron des Armes pour Débutants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#arme' },
    { id: 'm47',  type: 'artisant', gx: 1703, gy: 4125, name: "Forgeron d'Armures",               desc: "Forgeron des Armures pour Débutants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#armure' },
    { id: 'm48',  type: 'artisant', gx: 1703, gy: 4125, name: "Forgeron d'Accessoires",           desc: "Forgeron des Accessoires pour Débutants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#accessoires-base' },
    { id: 'm49',  type: 'artisant', gx: 1721, gy: 4605, name: 'Marchand Étrange',                 desc: "Marchand suspect trainant derrière la Cathédrale", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#marchand-etrange' },
    { id: 'm50',  type: 'artisant', gx: 1725, gy: 4672, name: "Forgeron d'Accessoires en Cuivre", desc: "Forgeron des Accessoires en Cuivre pour Débutants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#accessoires-cuivre' },
    { id: 'm51',  type: 'artisant', gx: 1725, gy: 4672, name: "Forgeron d'Accessoires en Fer",    desc: "Forgeron des Accessoires en Fer pour Débutants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#accessoires-fer' },
    { id: 'm52',  type: 'artisant', gx: 1725, gy: 4672, name: 'Refaçonneur',                      desc: "Permet la fabrication de ficelle en tout genre", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/refaconneurs#ville-de-depart' },
    { id: 'm53',  type: 'artisant', gx: 2322, gy: 3560, name: 'Forgeron de Lingots',              desc: "Forgeron de Lingots de Cuivre et de Fer", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#lingots' },
    { id: 'm54a', type: 'artisant', gx: 3193, gy: 1474, name: "Forgeron d'Armes",                 desc: "Forgeron des Armes pour Confirmés", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#arme-1' },
    { id: 'm54b', type: 'artisant', gx: 3193, gy: 1474, name: "Forgeron d'Armures",               desc: "Forgeron des Armures pour Confirmés", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#armure-1' },
    { id: 'm55',  type: 'artisant', gx: 2355, gy: 2412, name: "Forgeron d'Armes",                 desc: "Forgeron d'Armes du Donjon du Labyrinthe des Déchus", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#arme-2' },
    { id: 'm56',  type: 'artisant', gx: 2355, gy: 2412, name: "Forgeron d'Armures",               desc: "Forgeron d'Armures du Donjon du Labyrinthe des Déchus", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#armure-2' },
    { id: 'm57',  type: 'artisant', gx: 2394, gy: 4293, name: 'Bucheron',                         desc: "Bucheron permettant la Réalisation de Planches", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/bucherons#ville-de-depart' },
    { id: 'm58',  type: 'artisant', gx: 1712, gy: 4091, name: 'Alchimiste',                       desc: "Alchimiste permettant la Réalisation de Potions et Cristaux", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/alchimistes#ville-de-depart' },
    { id: 'm125', type: 'artisant', gx: 3257, gy: 1626, name: 'Alchimiste',                       desc: "Alchimiste de Tolbana", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/alchimistes#tolbana' },

    { id: 'm59',  type: 'repreneur_butin', gx: 1720, gy: 4170, name: 'Repreneur des Débutants',       desc: "Achète des ressources digne d'un Débutant", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/repreneurs-de-butins#ville-de-depart' },
    { id: 'm60',  type: 'repreneur_butin', gx: 1446, gy: 3415, name: 'Repreneur de la Forêt',         desc: "Achète des ressources de la Forêt", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/repreneurs-de-butins#hanaka' },
    { id: 'm61',  type: 'repreneur_butin', gx: 3074, gy: 3678, name: 'Repreneur Champêtre',           desc: "Achète des ressources des Champs", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/repreneurs-de-butins#mizunari' },
    { id: 'm62',  type: 'repreneur_butin', gx: 363,  gy: 3092, name: 'Repreneur des Maraicages',      desc: "Achète des ressources Gluantes", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/repreneurs-de-butins#vallaht' },
    { id: 'm63',  type: 'repreneur_butin', gx: 1541, gy: 1983, name: 'Repreneur des Mers',            desc: "Achète des ressources Maritimes", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/repreneurs-de-butins#virelune' },
    { id: 'm64',  type: 'repreneur_butin', gx: 2764, gy: 4680, name: 'Repreneur de Squelette',        desc: "Achète des ressources venant des Morts", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/repreneurs-de-butins#chateau-abandonne' },
    { id: 'm124', type: 'repreneur_butin', gx: 3217, gy: 1645, name: 'Repreneur Agguerie de Tolbana', desc: "Achète des ressources digne d'un Combattant Agguerie", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/repreneurs-de-butins#tolbana' },

    { id: 'm65a', type: 'marchand', gx: 1720, gy: 4147, name: "Marchand d'Équipement",    desc: "Vends des Armes et objets pour les Nouveaux Arrivants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#ville-de-depart' },
    { id: 'm66',  type: 'marchand', gx: 1447, gy: 3390, name: "Marchand d'Équipement",    desc: "Vends des Armes et objets pour les Nouveaux Arrivants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#hanaka' },
    { id: 'm123', type: 'marchand', gx: 438,  gy: 3077, name: "Marchand d'Accessoires",   desc: "Vends des Accessoires Gluants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#vallhat' },
    { id: 'm67',  type: 'marchand', gx: 3241, gy: 1626, name: "Marchand d'Accessoires",   desc: "Vends des Accessoires Résistants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#tolbana-1' },
    { id: 'm68a', type: 'marchand', gx: 1750, gy: 4147, name: "Marchand d'Outils",        desc: "Vends des outils pour récolter des matières premières", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#ville-de-depart-1' },
    { id: 'm69a', type: 'marchand', gx: 1537, gy: 1958, name: "Marchand d'Outils",        desc: "Vends des outils pour récolter des matières premières", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#virelune' },
    { id: 'm69b', type: 'marchand', gx: 1940, gy: 843,  name: "Marchand d'Outils",        desc: "Vends des outils pour récolter des matières premières", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#tolbana-3' },
    { id: 'm70',  type: 'marchand', gx: 3230, gy: 1658, name: "Marchand de Consommables", desc: "Vends des Utilitaires comme des Potions ou des Parchemins", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#tolbana-2' },
    { id: 'm65b', type: 'marchand', gx: 3240, gy: 1658, name: "Marchand d'Équipement",    desc: "Vends des Armes et objets", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#tolbana' },
    { id: 'm68b', type: 'marchand', gx: 3257, gy: 1638, name: "Marchand d'Outils",        desc: "Vends des outils de Candelia", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#candelia' },

    { id: 'm71', type: 'clef', emoji: '🗝️', gx: 1750, gy: 4170, name: 'Clef du Donjon Mine de Geldorak',      desc: "Clef permettant d'ouvrir la porte du Donjon des Mines de Geldorak",     link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/fabricants-clefs-et-secret#ville-de-depart' },
    { id: 'm72', type: 'clef', emoji: '🗝️', gx: 4210, gy: 3895, name: 'Clef du Donjon Mine de Geldorak',      desc: "Clef permettant d'ouvrir la porte du Donjon des Mines de Geldorak",     link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/fabricants-clefs-et-secret#mine-de-geldorak' },
    { id: 'm73', type: 'clef', emoji: '🗝️', gx: 2314, gy: 2435, name: 'Clef du Donjon Labyrinthe des Déchus', desc: "Clef permettant d'ouvrir la porte du Donjon du Labyrinthe des Déchus", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/fabricants-clefs-et-secret#labyrinthe-des-dechus' },
    { id: 'm74', type: 'clef', emoji: '🗝️', gx: 955,  gy: 1212, name: "Clef du Donjon Xal'Zirith",            desc: "Clef permettant d'ouvrir la porte du Donjon Xal'Zirith",                link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/fabricants-clefs-et-secret#xalzirith' },
    { id: 'm75', type: 'clef', emoji: '🗝️', gx: 1936, gy: 835,  name: "Clef du Donjon Xal'Zirith",            desc: "Clef permettant d'ouvrir la porte du Donjon Xal'Zirith",                link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/fabricants-clefs-et-secret#candelia' },
    { id: 'm76', type: 'clef', emoji: '💍', gx: 4128, gy: 1823, name: "Fabricant Secret de l'Ours",            desc: "Permet la confection Secrète du Bracelet de Glace",     link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/fabricants-clefs-et-secret#citadelle-des-neiges' },
    { id: 'm77', type: 'clef', emoji: '💍', gx: 1267, gy: 2140, name: 'Fabricant Secret du Léviathan',         desc: "Permet la confection Secrète de l'Anneau du Léviathan", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/fabricants-clefs-et-secret#antre-de-aepep' },
    { id: 'm78', type: 'clef', emoji: '💍', gx: 387,  gy: 3097, name: 'Fabricant Secret des Slimes',           desc: "Permet la confection Secrète de l'Anneau Gluant",       link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/fabricants-clefs-et-secret#vallhat' },
    { id: 'm79', type: 'clef', emoji: '💍', gx: 1092, gy: 1193, name: "Fabricant Secret des Araignées",        desc: "Permet la confection Secrète du Collier d'Aragorn",     link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/fabricants-clefs-et-secret#arakhnol' },

    { id: 'm80',  type: 'quête_secondaire', gx: 1819, gy: 4002, name: "Tilda",      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/tilda' },
    { id: 'm81',  type: 'quête_secondaire', gx: 1817, gy: 3971, name: "Lila",       desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/lila' },
    { id: 'm82',  type: 'quête_secondaire', gx: 2000, gy: 4280, name: "Varn",       desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/varn' },
    { id: 'm83',  type: 'quête_secondaire', gx: 1682, gy: 4720, name: "Orin",       desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/ori' },
    { id: 'm84',  type: 'quête_secondaire', gx: 1682, gy: 4720, name: "Inari",      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/inari' },
    { id: 'm85',  type: 'quête_secondaire', gx: 1210, gy: 4296, name: "Meiko",      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/meiko' },
    { id: 'm86',  type: 'quête_secondaire', gx: 1214, gy: 4313, name: "Saria",      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/saria' },
    { id: 'm87',  type: 'quête_secondaire', gx: 1493, gy: 4306, name: "Rikyu",      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/rikyu' },
    { id: 'm88',  type: 'quête_secondaire', gx: 1473, gy: 4321, name: "Bunta",      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/bunta' },
    { id: 'm89',  type: 'quête_secondaire', gx: 1579, gy: 4037, name: "Nacht",      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/nacht' },
    { id: 'm90',  type: 'quête_secondaire', gx: 2143, gy: 4177, name: "Millia",     desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/millia' },
    { id: 'm91',  type: 'quête_secondaire', gx: 1475, gy: 3373, name: "Genzo",      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/hanaka/genzo' },
    { id: 'm92',  type: 'quête_secondaire', gx: 1462, gy: 3373, name: "Bartok",     desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/hanaka/bartok' },
    { id: 'm93',  type: 'quête_secondaire', gx: 1377, gy: 3406, name: "Greta",      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/hanaka/greta' },
    { id: 'm94',  type: 'quête_secondaire', gx: 1351, gy: 3433, name: "Soeur Therra", desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/hanaka/soeur-therra' },
    { id: 'm95',  type: 'quête_secondaire', gx: 1435, gy: 3532, name: "Rina",       desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/hanaka/rina' },
    { id: 'm96',  type: 'quête_secondaire', gx: 1446, gy: 3560, name: "Maya",       desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/hanaka/maya' },
    { id: 'm97',  type: 'quête_secondaire', gx: 1296, gy: 3438, name: "Toban",      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/hanaka/toban' },
    { id: 'm98',  type: 'quête_secondaire', gx: 3317, gy: 2954, name: "Fira",       desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/camp-militaire/fira' },
    { id: 'm99',  type: 'quête_secondaire', gx: 3216, gy: 2913, name: "Corentin",   desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/camp-militaire/corentin' },
    { id: 'm100', type: 'quête_secondaire', gx: 3146, gy: 2898, name: "Jean",       desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/camp-militaire/jean' },
    { id: 'm101', type: 'quête_secondaire', gx: 3011, gy: 1918, name: "Horace",     desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/tolbana/horace' },
    { id: 'm102', type: 'quête_secondaire', gx: 1807, gy: 2127, name: "Haruto",     desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/virelune/haruto' },
    { id: 'm103', type: 'quête_secondaire', gx: 1838, gy: 2019, name: "Sam",        desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/virelune/sam' },
    { id: 'm104', type: 'quête_secondaire', gx: 1506, gy: 1980, name: "Juliette",   desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/virelune/juliette' },
    { id: 'm105', type: 'quête_secondaire', gx: 1500, gy: 2015, name: "Monique",    desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/virelune/monique' },
    { id: 'm106', type: 'quête_secondaire', gx: 1565, gy: 1860, name: "Luc",        desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/virelune/luc' },
    { id: 'm107', type: 'quête_secondaire', gx: 1645, gy: 1042, name: "Gilbert",    desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/candelia/gilbert' },
    { id: 'm108', type: 'quête_secondaire', gx: 1958, gy: 901,  name: "Pierre",     desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/candelia/pierre' },
    { id: 'm109', type: 'quête_secondaire', gx: 1952, gy: 859,  name: "Yannis",     desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/candelia/yannis' },
    { id: 'm110', type: 'quête_secondaire', gx: 1927, gy: 863,  name: "Roméo",      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/candelia/roméo' },
    { id: 'm111', type: 'quête_secondaire', gx: 1895, gy: 848,  name: "Tomoko",     desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/candelia/tomoko' },
    { id: 'm112', type: 'quête_secondaire', gx: 1891, gy: 814,  name: "Gilmar",     desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/candelia/gilmar' },
    { id: 'm113', type: 'quête_secondaire', gx: 1815, gy: 777,  name: "Émilie",     desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/candelia/emilie' },
    { id: 'm114', type: 'quête_secondaire', gx: 3077, gy: 3711, name: "Phares",     desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/mizunari/phares' },
    { id: 'm115', type: 'quête_secondaire', gx: 3060, gy: 3692, name: "Louise",     desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/mizunari/louise' },
    { id: 'm116', type: 'quête_secondaire', gx: 3038, gy: 3699, name: "Elwyn",      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/mizunari/elwyn' },
    { id: 'm117', type: 'quête_secondaire', gx: 3050, gy: 3661, name: "Michelle",   desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/mizunari/michelle' },
    { id: 'm118', type: 'quête_secondaire', gx: 3069, gy: 3668, name: "Martine",    desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/mizunari/martine' },
    { id: 'm119', type: 'quête_secondaire', gx: 455,  gy: 3066, name: "Par les Branches des Anciens", desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/vallhat/par-les-branches-des-anciens' },
    { id: 'm120', type: 'quête_secondaire', gx: 442,  gy: 3029, name: "Saya",       desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/vallhat/saya' },
    { id: 'm121', type: 'quête_secondaire', gx: 416,  gy: 3008, name: "Ayaka",      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/vallhat/ayaka' },
    { id: 'm122', type: 'quête_secondaire', gx: 382,  gy: 3046, name: "Daiki",      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/vallhat/daiki' },
  ],
  2: [],
};

const MAP_CALIBRATION = {
  1: {
    centerPixel: { x: 450,    y: 450  },
    centerGame:  { x: 2474.5, y: 2570 },
    radiusPixel: 450,
    radiusGame:  2474.5,
  },
  2: {
    centerPixel: { x: 450, y: 450 },
    centerGame:  { x: 0,   y: 0   },
    radiusPixel: 450,
    radiusGame:  1000,
  }
};