const FLOOR_COUNT = 100;

const MARKER_EMOJI = {
  région:           '📍',
  zone_monstre:     '💀',
  quête_principale: '💬',
  quête_secondaire: '❓',
  repreneur_butin:  '🛒',
  marchand:         '💰',
  artisant:         '⚒️',
  clef:             '🗝️',
  ressource:        '🌿',
  donjon:           '⚔️',
};

const FLOOR_NAMES = {
  1: 'Forêt',
  2: 'Désert',
};

const FLOOR_DATA = {
  1: { hasUnderground: false  },
  2: { hasUnderground: true }
};

const FLOOR_ZONES = {
  1: [
    {
      id: 'm1z1',
      name: 'Vallée des Loups',
      regionName: 'Vallée des Loups',
      color: '#e0ac60',
      emoji: '🐺',
      monsters: [
        { name: 'Loup Sinitre Blanc', level: 2, difficulty: '⭐',   emoji: '🐺', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/vallee-des-loups/loups-sinistres' },
        { name: 'Loup Sinitre Noir',  level: 2, difficulty: '⭐',   emoji: '🐺', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/vallee-des-loups/loups-sinistres' },
        { name: 'Albal',              level: 2, difficulty: '⭐⭐', emoji: '🐺', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/vallee-des-loups/albal' },
      ],
      points: [
        { gx: 2356, gy: 4026 }, { gx: 2270, gy: 3943 }, { gx: 2306, gy: 3784 },
        { gx: 2400, gy: 3651 }, { gx: 2583, gy: 3667 }, { gx: 2628, gy: 3849 },
        { gx: 2571, gy: 3982 },
      ],
    },
    {
      id: 'm1z2',
      name: 'Zone des Sangliers',
      regionName: 'Zone des Sangliers',
      color: '#644d58',
      emoji: '🐗',
      monsters: [
        { name: 'Sanglier Corrompu', level: 2, difficulty: '⭐',   emoji: '🐗', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/zone-sanglier/sanglier-corrompu' },
        { name: 'Pumba',             level: 2, difficulty: '⭐⭐', emoji: '🐗', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/zone-sanglier/pumba' },
      ],
      points: [
        { gx: 1537, gy: 3620 }, { gx: 1707, gy: 3344 }, { gx: 1912, gy: 3339 },
        { gx: 2060, gy: 3470 }, { gx: 2057, gy: 3713 }, { gx: 1783, gy: 3619 },
      ],
    },
    {
      id: 'm1z3',
      name: 'Champs de Mizunari',
      color: '#82e753',
      emoji: '🌾',
      monsters: [
        { name: 'Nephentes', level: 4, difficulty: '⭐⭐', emoji: '🥬', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/mizunari/nephentes' },
      ],
      points: [
        { gx: 3232, gy: 3731 }, { gx: 3286, gy: 3708 }, { gx: 3349, gy: 3771 },
        { gx: 3292, gy: 3828 }, { gx: 3252, gy: 3786 },
      ],
    },
    {
      id: 'm1z4',
      name: 'Marécage Putride',
      regionName: 'Marécage Putride',
      color: '#ee7560',
      emoji: '🍄',
      monsters: [
        { name: 'Mini Tréant',       level: 3, difficulty: '⭐⭐',   emoji: '🌿', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/hanaka/mini-treant' },
        { name: 'Guerrier Tréant',   level: 3, difficulty: '⭐⭐',   emoji: '🛡️', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/hanaka/guerrier-treant' },
        { name: "Tréant d'Élite",    level: 3, difficulty: '⭐⭐',   emoji: '🏹', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/hanaka/treant-elite' },
        { name: 'Mage Sylvestre',    level: 3, difficulty: '⭐⭐',   emoji: '🧙', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/hanaka/mage-sylvestre' },
        { name: 'Gardien Colossal',  level: 3, difficulty: '⭐⭐⭐', emoji: '🌳', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/hanaka/gardien-colossal' },
      ],
      points: [
        { gx: 1589, gy: 3261 }, { gx: 1432, gy: 3269 }, { gx: 989, gy: 3272 },
        { gx: 954, gy: 3146 },  { gx: 1003, gy: 2934 }, { gx: 1328, gy: 2938 },
        { gx: 1519, gy: 2831 }, { gx: 1668, gy: 3084 },
      ],
    },
    {
      id: 'm1z5',
      name: 'Vallhat',
      regionName: 'Vallhat',
      color: '#74ce50',
      emoji: '🌳',
      monsters: [
        { name: 'Petit Slime',      level: 3, difficulty: '⭐⭐',    emoji: '🟢', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/vallhat/petit-slime' },
        { name: 'Guerrier Slime',   level: 3, difficulty: '⭐⭐',    emoji: '⚔️', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/vallhat/guerrier-slime' },
        { name: 'Slime Soigneur',   level: 3, difficulty: '⭐⭐⭐',  emoji: '⛑️', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/vallhat/slime-soigneur' },
        { name: 'Slime Magicien',   level: 3, difficulty: '⭐⭐⭐',  emoji: '🧙', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/vallhat/slime-magicien' },
        { name: 'Gorbel',           level: 3, difficulty: '⭐⭐⭐⭐',emoji: '👑', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/vallhat/gorbel' },
      ],
      points: [
        { gx: 515, gy: 3184 }, { gx: 387, gy: 3378 }, { gx: 238, gy: 3398 },
        { gx: 129, gy: 3104 }, { gx: 90, gy: 2795 },   { gx: 266, gy: 2693 },
        { gx: 498, gy: 2796 }, { gx: 595, gy: 3025 },
      ],
    },
    {
      id: 'm1z6',
      name: 'Ruines Maudites',
      color: '#eecf21',
      emoji: '💀',
      monsters: [
        { name: 'Squelette Épéiste',      level: 3, difficulty: '⭐⭐',   emoji: '💀', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/ruines-maudites/squelette-epeiste' },
        { name: 'Guerrier Squelette',     level: 3, difficulty: '⭐⭐⭐', emoji: '⚔️', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/ruines-maudites/guerrier-squelette' },
        { name: 'Squelette Hallebardier', level: 3, difficulty: '⭐⭐⭐', emoji: '🔨', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/ruines-maudites/squelette-hallbardier' },
      ],
      points: [
        { gx: 2692, gy: 4371 }, { gx: 2757, gy: 4375 }, { gx: 2815, gy: 4427 },
        { gx: 2808, gy: 4497 }, { gx: 2693, gy: 4470 },
      ],
    },
    {
      id: 'm1z7',
      name: 'Mine de Geldorak',
      regionName: 'Mine de Geldorak',
      color: '#75bdcf',
      emoji: '⛰️',
      monsters: [
        { name: 'Bandit Archer',   level: 3, difficulty: '⭐⭐', emoji: '🏹', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/mine-de-geldorak/bandit-archer' },
        { name: 'Bandit Assassin', level: 3, difficulty: '⭐⭐', emoji: '🗡️', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/mine-de-geldorak/bandit-assassin' },
        { name: 'Bandit Robuste',  level: 3, difficulty: '⭐⭐', emoji: '💪', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/mine-de-geldorak/bandit-robuste' },
      ],
      points: [
        { gx: 3922, gy: 3824 }, { gx: 4081, gy: 3834 }, { gx: 4201, gy: 3880 },
        { gx: 4083, gy: 3985 }, { gx: 3994, gy: 4036 }, { gx: 3916, gy: 3971 },
        { gx: 3907, gy: 3887 },
      ],
    },
    {
      id: 'm1z8',
      name: "Archipel d'Ika",
      regionName: "Archipel d'Ika",
      color: '#3e9db4',
      emoji: '🏝️',
      monsters: [
        { name: 'Ika', level: 3, difficulty: '⭐⭐⭐', emoji: '🐢', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/archipel-dika/ika' },
      ],
      points: [
        { gx: 3130, gy: 4055 }, { gx: 3163, gy: 4008 }, { gx: 3243, gy: 4010 },
        { gx: 3320, gy: 4084 }, { gx: 3321, gy: 4143 }, { gx: 3268, gy: 4185 },
        { gx: 3142, gy: 4180 }, { gx: 3113, gy: 4084 },
      ],
    },
    {
      id: 'm1z9',
      name: "Arakh'Nol",
      regionName: "Arakh'Nol",
      color: '#8bbeca',
      emoji: '🕸️',
      monsters: [
        { name: 'Araignée des Forêts', level: 7, difficulty: '⭐⭐⭐⭐', emoji: '🕷️', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-nord/arakhnol/araignees-des-forets' },
      ],
      points: [
        { gx: 1394, gy: 1186 }, { gx: 1472, gy: 1451 }, { gx: 1358, gy: 1489 },
        { gx: 1332, gy: 1581 }, { gx: 1152, gy: 1701 }, { gx: 1029, gy: 1743 },
        { gx: 990, gy: 1710 },  { gx: 1096, gy: 1512 }, { gx: 1085, gy: 1395 },
        { gx: 1138, gy: 1309 }, { gx: 989, gy: 1207 },  { gx: 1032, gy: 1146 },
        { gx: 1247, gy: 1210 },
      ],
    },
    {
      id: 'm1z10',
      name: 'Montagnes de Tolbana',
      color: '#ddb04e',
      emoji: '🏔️',
      monsters: [
        { name: 'Cerf des Montagnes', level: 7, difficulty: '⭐⭐⭐', emoji: '🦌', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-nord/tolbana/cerf-des-montagnes' },
      ],
      points: [
        { gx: 3945, gy: 1203 }, { gx: 4027, gy: 1066 }, { gx: 4187, gy: 1082 },
        { gx: 4115, gy: 1196 }, { gx: 4119, gy: 1280 }, { gx: 3998, gy: 1261 },
      ],
    },
    {
      id: 'm1z11',
      name: 'Citadelle des Neiges',
      regionName: 'Citadelle des Neiges',
      color: '#224ba5',
      emoji: '❄️',
      monsters: [
        { name: 'Golem de Glace',   level: 7, difficulty: '⭐⭐⭐',    emoji: '🧊', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-nord/citadelle-des-neiges/golem-de-glace' },
        { name: 'Spirite de Glace', level: 7, difficulty: '⭐⭐⭐',    emoji: '🦋', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-nord/citadelle-des-neiges/spirite-de-glace' },
        { name: 'Ours de Glace',    level: 7, difficulty: '⭐⭐⭐⭐⭐',emoji: '🐻', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-nord/citadelle-des-neiges/ours-de-glace' },
      ],
      points: [
        { gx: 3969, gy: 2013 }, { gx: 3967, gy: 2039 }, { gx: 3943, gy: 2048 },
        { gx: 3886, gy: 2045 }, { gx: 3886, gy: 2007 }, { gx: 3907, gy: 1998 },
        { gx: 3945, gy: 1999 },
      ],
    },
    {
      id: 'm1z12',
      name: 'Lac de Virelune',
      regionName: 'Antre de Aepep',
      color: '#bde3f1',
      emoji: '🎣',
      monsters: [
        { name: 'Poisson Requin', level: 7, difficulty: '⭐⭐⭐',    emoji: '🦈', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-nord/virelune/poisson-requin' },
        { name: 'Nymbréa',        level: 7, difficulty: '⭐⭐⭐⭐⭐',emoji: '🐟', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-nord/virelune/nymbrea' },
      ],
      points: [
        { gx: 1399, gy: 2022 }, { gx: 1397, gy: 2105 }, { gx: 1336, gy: 2141 },
        { gx: 1270, gy: 2106 }, { gx: 1256, gy: 2042 }, { gx: 1316, gy: 1986 },
        { gx: 1369, gy: 1999 },
      ],
    },
    {
      id: 'm1z13',
      name: 'Prairie des Sangliers',
      color: '#644d58',
      emoji: '🐗',
      monsters: [
        { name: 'Sanglier Corrompu', level: 2, difficulty: '⭐', emoji: '🐗', link: 'https://guilde-sao.gitbook.io/watchers/paliers/monstres/carte-du-sud/zone-sanglier/sanglier-corrompu' },
      ],
      points: [
        { gx: 2610, gy: 2304 }, { gx: 2492, gy: 2220 }, { gx: 2521, gy: 2015 },
        { gx: 2739, gy: 2117 }, { gx: 2650, gy: 2259 },
      ],
    },
  ],
  2: [
    {
      id: 'm2z1',
      name: 'Lac des Taureaux',
      regionName: 'Lac des Taureaux',
      color: '#39494e',
      emoji: '🐂',
      monsters: [
        { name: 'Taureau', level: 10, difficulty: '⭐', emoji: '🐃', link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/lac-des-taureaux/taureau' },
        { name: 'Taureau Monstrueux', level: 10, difficulty: '⭐', emoji: '🐃', link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/lac-des-taureaux/taureau_monstrueux' },
        ],
        points: [
          { gx: 151, gy: -135 }, { gx: 200, gy: -81 }, { gx: 175, gy: -9 },
          { gx: 92, gy: 4 }, { gx: 20, gy: -75 }, { gx: 36, gy: -118 },
        ]
    },
    {
      id: 'm2z2',
      name: 'Forêt Sucrée',
      regionName: 'Forêt Sucrée',
      color: '#53cb38',
      emoji: '🍯',
      monsters: [
        { name: 'Ours de la Forêt', level: 11, difficulty: '⭐', emoji: '🐻', link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/lforêt-sucrée/ours-de-la-foret' },
        { name: 'Winnie', level: 11, difficulty: '⭐⭐⭐', emoji: '🐻', link: '' },
        ],
        points: [
          { gx: 294, gy: -625 }, { gx: 334, gy: -709 }, { gx: 541, gy: -719 },
          { gx: 561, gy: -560 }, { gx: 455, gy: -544 }, { gx: 386, gy: -584 }, { gx: 332, gy: -563 },
        ]
    },
    {
      id: 'm2z3',
      name: 'Désert des Crocs Argentés',
      regionName: 'Désert des Crocs Argentés',
      color: '#f3c26f',
      emoji: '🐺',
      monsters: [
        { name: 'Loups des Montagnes', level: 10, difficulty: '⭐⭐', emoji: '🐺', link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/desert-des-crocs-argentes/loups-des-montagnes' },
        { name: 'Loups des Savanes', level: 10, difficulty: '⭐⭐', emoji: '🐺', link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/desert-des-crocs-argentes/loups-des-savanes' },
      ],
      points: [
        { gx: -207, gy: -593 }, { gx: -263, gy: -481 }, { gx: -528, gy: -395 },
        { gx: -561, gy: -476 }, { gx: -529, gy: -542 }, { gx: -372, gy: -568 },
      ]
    },
    {
      id: 'm2z4',
      name: 'Forêt des Ailes d\'Émeraude',
      regionName: 'Forêt des Ailes d\'Émeraude',
      color: '#53cb38',
      emoji: '🍃',
      monsters: [
        { name: 'Harpie de Terre', level: 12, difficulty: '⭐⭐', emoji: '🦅', link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/foret-des-ailes-demeraude/harpie-de-terre' },
        ],
        points: [
          { gx: -583, gy: 385 }, { gx: -568, gy: 374 }, { gx: -531, gy: 410 },
          { gx: -494, gy: 394 }, { gx: -476, gy: 472 }, { gx: -515, gy: 528 }, { gx: -553, gy: 501 }, { gx: -538, gy: 451 }, { gx: -551, gy: 421 },
        ]
    },
    {
      id: 'm2z5',
      name: 'Baie des Monstres Ondoyante',
      regionName: 'Baie des Monstres Ondoyante',
      color: '#6363d7',
      emoji: '🌊',
      monsters: [
        { name: 'Harpie de Foudre', level: 12, difficulty: '⭐⭐', emoji: '🦅', link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/baie-des-monstres-ondoyante/harpie-de-foudre' },
        { name: 'Poisson Fulgurant', level: 12, difficulty: '⭐', emoji: '🐟', link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/baie-des-monstres-ondoyante/poisson-fulgurant' },
        ],
        points: [
          { gx: -519, gy: -48 }, { gx: -452, gy: 76 }, { gx: -533, gy: 193 },
          { gx: -721, gy: 220 }, { gx: -766, gy: 266 }, { gx: -839, gy: 211 }, { gx: -754, gy: 48 }, { gx: -675, gy: 54 },
        ]
    },
    {
      id: 'm2z6',
      name: 'Sanctuaire de Khesûn',
      regionName: 'Sanctuaire de Khesûn',
      color: '#e0e02c',
      emoji: '🛕',
      monsters: [
        { name: 'Squelette du Sanctuaire - Archer', level: 13, difficulty: '⭐⭐', emoji: '🏹', link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/sanctuaire-de-khesun/squelette-du-sanctuaire-archer' },
        { name: 'Squelette du Sanctuaire - Shaman', level: 13, difficulty: '⭐⭐', emoji: '🌿', link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/sanctuaire-de-khesun/squelette-du-sanctuaire-shaman' },
        { name: 'Squelette du Sanctuaire - Guerrier', level: 13, difficulty: '⭐⭐⭐', emoji: '⚔️', link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/sanctuaire-de-khesun/squelette-du-sanctuaire-guerrier' },
        { name: 'Gardien du Sanctuaire', level: 13, difficulty: '⭐⭐⭐⭐⭐', emoji: '☠️', link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/sanctuaire-de-khesun/gardien-du-sanctuaire'},
        { name: 'Minion du Gardien', level: 13, difficulty: '⭐', emoji: '🦴', link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/sanctuaire-de-khesun/minion-du-gardien'},
        ],
        points: [
          { gx: -18, gy: 123 }, { gx: 14, gy: 127 }, { gx: 36, gy: 172 },
          { gx: 36, gy: 200 }, { gx: -23, gy: 223 }, { gx: -47, gy: 218 }, { gx: -47, gy: 191 },
        ]
    },
    {
      id: 'm2z7',
      name: 'Oasis Secret',
      regionName: 'Oasis Secret',
      color: '#98f8f9',
      emoji: '🏝️',
      monsters: [
        { name: 'Velindra la Tisseuse', level: 13, difficulty: '⭐⭐⭐⭐⭐', emoji: '🧙‍♀️', link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/oasis-secret/velindrala-tisseuse'},
        ],
        points: [
          { gx: 754, gy: 301 }, { gx: 766, gy: 248 }, { gx: 816, gy: 225 },
          { gx: 833, gy: 260 }, { gx: 795, gy: 284 },
        ]
    },
  ],
};

const FLOOR_ZONES_UNDERGROUND = {
  2: [
    {
      id: 'm2z1u1',
      name: 'Nid de Brasier',
      regionName: 'Nid de Brasier',
      color: '#df6c42',
      emoji: '🔥',
      monsters: [
        { name: 'Harpie de Feu', level: 12, difficulty: '⭐⭐', emoji: '🦅', link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/nid-de-brasier/harpie-de-feu' },
      ],
      points: [
        { gx: -431, gy: 192 }, { gx: -506, gy: 317 }, { gx: -649, gy: 232 },
        { gx: -680, gy: 231 }, { gx: -687, gy: 221 }, { gx: -677, gy: 208 }, { gx: -626, gy: 179 }, { gx: -538, gy: 152 }
      ],
    },
    {
      id: 'm2z2u1',
      name: 'Les Veines de Sablemor',
      regionName: 'Les Veines de Sablemor',
      color: '#ded26b',
      emoji: '🕳️',
      monsters: [
        { name: 'Golem de Pierre', level: 13, difficulty: '⭐⭐⭐', emoji: '🗿', link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/les-veines-de-sablemor/golem-de-pierre' },
        { name: 'Magnus, Colosse des Veines', level: 13, difficulty: '⭐⭐⭐⭐⭐', emoji: '🛡️', link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/les-veines-de-sablemor/magnus-colosse-des-veines' },
      ],
      points: [
        { gx: 226, gy: 341 }, { gx: 166, gy: 327 }, { gx: 154, gy: 298 },
        { gx: 156, gy: 269 }, { gx: 181, gy: 234 }, { gx: 238, gy: 234 }, { gx: 267, gy: 267 }, { gx: 256, gy: 326 }
      ],
    },
  ],
};

const FLOOR_MARKERS = {
  1: [
    { id: 'm1d2',  type: 'donjon',  gx: 2709, gy: 4408, name: 'Sous-Donjon Nasgul',                 desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/donjons/donjon-squelette' },
    { id: 'm1d3',  type: 'donjon',  gx: 4210, gy: 3895, name: 'Donjon Mine de Geldorak',            desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/donjons/donjon-geldorak' },
    { id: 'm1d4',  type: 'donjon',  gx: 2300, gy: 2400, name: "Donjon Labyrinthe des Déchus",       desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/donjons/donjon-labyrinthe-des-dechus' },
    { id: 'm1d5',  type: 'donjon',  gx: 955,  gy: 1212, name: "Donjon Xal'Zirith",                  desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/donjons/donjon-xalzirith' },

    { id: 'm1r1',  type: 'région',  gx: 1737, gy: 4300, name: 'Ville de Départ',                    desc: "La ville de départ est un havre paisible dans un monde virtuel encore inconnu. C'est ici que chaque aventure commence", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/ville-de-depart' },
    { id: 'm1r2',  type: 'région',  gx: 1395, gy: 3450, name: 'Hanaka',                             desc: "Un hameau boisé niché entre les collines où les sangliers rôdent à la lisière. Berceau des premiers affrontements", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/hanaka' },
    { id: 'm1r3',  type: 'région',  gx: 2450, gy: 3853, name: 'Vallée des Loups',                   desc: "Un vallon brumeux où résonnent encore les hurlements.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/vallee-des-loups' },
    { id: 'm1r4',  type: 'région',  gx: 1213, gy: 3108, name: 'Marécage Putride',                   desc: "Un marais dense et hostile, où la brume empoisonne l'air.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/marecage-putride' },
    { id: 'm1r5',  type: 'région',  gx: 1800, gy: 3500, name: 'Zone des Sangliers',                 desc: "Un territoire sauvage où les sangliers règnent.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/zone-sanglier' },
    { id: 'm1r6',  type: 'région',  gx: 948,  gy: 4189, name: 'Vallée des Pétales',                 desc: "Une vallée enchantée où les pétales dansent au vent.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/vallee-des-petales' },
    { id: 'm1r7',  type: 'région',  gx: 2764, gy: 4680, name: 'Château Abandonné',                  desc: "Les ruines d'un château oublié, rongé par le temps.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/chateau-abandonne' },
    { id: 'm1r8',  type: 'région',  gx: 3054, gy: 3684, name: 'Mizunari',                           desc: "Petit village paisible niché au bord d'un lac clair.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/mizunari' },
    { id: 'm1r9',  type: 'région',  gx: 3221, gy: 4097, name: "Archipel d'Ika",                     desc: "Un archipel tropical où les tortues géantes se rassemblent.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/archipel-dika' },
    { id: 'm1r10', type: 'région',  gx: 2249, gy: 3210, name: 'Quartier OG',                        desc: "Le bastion de la Guilde OG, réputée et redoutée.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/quartier-og' },
    { id: 'm1r11', type: 'région',  gx: 935,  gy: 3580, name: 'Cyclorim',                           desc: "Une arène antique taillée dans la roche rouge.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/cyclorim' },
    { id: 'm1r12', type: 'région',  gx: 3978, gy: 3909, name: 'Mine de Geldorak',                   desc: "Creusée au coeur de la montagne.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/mine-de-geldorak' },
    { id: 'm1r13', type: 'région',  gx: 2834, gy: 3018, name: 'CastelBrume',                        desc: "Perché au sommet d'une crête oubliée.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/castelbrume' },
    { id: 'm1r14', type: 'région',  gx: 390,  gy: 3041, name: 'Vallhat',                            desc: "Perchée au sommet d'un massif venteux.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/vallhat' },
    { id: 'm1r15', type: 'région',  gx: 3937, gy: 2031, name: 'Citadelle des Neiges',               desc: "Autrefois bastion imprenable.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/citadelle-des-neiges' },
    { id: 'm1r16', type: 'région',  gx: 313,  gy: 2455, name: 'Jardin des Géants',                  desc: "Un lieu oublié où la nature a repris ses droits.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/jardin-des-geants' },
    { id: 'm1r17', type: 'région',  gx: 2454, gy: 2840, name: 'Le Lac des Nénuphars',               desc: "Calme et mystère entourent ses eaux troubles...", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/le-lac-des-nenuphars' },
    { id: 'm1r18', type: 'région',  gx: 3212, gy: 1639, name: 'Tolbana',                            desc: "Érigé à flanc de montagne.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/tolbana' },
    { id: 'm1r19', type: 'région',  gx: 1325, gy: 2068, name: 'Antre de Aepep',                     desc: "Au cœur d'une caverne oubliée dort un serpent ancien.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/antre-de-aepep' },
    { id: 'm1r20', type: 'région',  gx: 1490, gy: 1982, name: 'Virelune',                           desc: "Niché au bord d'un gouffre marin insondable.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/virelune' },
    { id: 'm1r21', type: 'région',  gx: 1852, gy: 735,  name: 'Candelia',                           desc: "Blotti entre les pics abrupts.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/candelia' },
    { id: 'm1r22', type: 'région',  gx: 3334, gy: 1038, name: 'Tour du Kobold',                     desc: "Une ancienne tour en ruine.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/tour-du-kobold' },
    { id: 'm1r23', type: 'région',  gx: 2343, gy: 1702, name: 'Mine de Pic de Cristal',             desc: "Cette ancienne mine renferme des cristaux.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/mine-de-pic-de-cristal' },
    { id: 'm1r24', type: 'région',  gx: 2969, gy: 1217, name: 'Cristal de Tolbana',                 desc: "Des cristaux luminescents aux propriétés mystérieuses.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/cristal-de-tolbana' },
    { id: 'm1r25', type: 'région',  gx: 1232, gy: 1400, name: "Arakh'Nol",                          desc: "Dans les profondeurs d'Arakh'Nol, la lumière peine à percer.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/arakhnol' },
    { id: 'm1r26', type: 'région',  gx: 4676, gy: 2438, name: 'Guilde Marchande',                   desc: "Le Quartier général de la Guilde des Marchands.", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/regions/guilde-marchande' },

    { id: 'm1t1',  type: 'ressource', emoji: '🌾', gx: 2263, gy: 3706, name: 'Allium',              desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/herboriste#alliums' },
    { id: 'm1t2',  type: 'ressource', emoji: '🌾', gx: 2288, gy: 3653, name: 'Blé',                 desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/herboriste#ble' },
    { id: 'm1t3',  type: 'ressource', emoji: '🌳', gx: 2846, gy: 3517, name: 'Chêne de Forêt',      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/bucheron#chene' },
    { id: 'm1t4',  type: 'ressource', emoji: '🌳', gx: 2357, gy: 4301, name: 'Chêne Proche',        desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/bucheron#chene' },
    { id: 'm1t5',  type: 'ressource', emoji: '🌳', gx: 1707, gy: 1207, name: 'Bouleau',             desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/bucheron#bouleau' },
    { id: 'm1t6',  type: 'ressource', emoji: '⛏️', gx: 2309, gy: 3509, name: 'Charbon Petite Cave', desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/mineur#charbon' },
    { id: 'm1t7',  type: 'ressource', emoji: '⛏️', gx: 2309, gy: 3509, name: 'Cuivre Petite Cave',  desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/mineur#cuivre' },
    { id: 'm1t8',  type: 'ressource', emoji: '⛏️', gx: 2309, gy: 3509, name: 'Fer Petite Cave',     desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/mineur#fer' },
    { id: 'm1t9',  type: 'ressource', emoji: '⛏️', gx: 903,  gy: 3448, name: 'Charbon Grande Cave', desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/mineur#charbon' },
    { id: 'm1t10', type: 'ressource', emoji: '⛏️', gx: 903,  gy: 3448, name: 'Cuivre Grande Cave',  desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/mineur#cuivre' },
    { id: 'm1t11', type: 'ressource', emoji: '⛏️', gx: 903,  gy: 3448, name: 'Fer Grande Cave',     desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/ressources/mineur#fer' },

    { id: 'm1a1',  type: 'artisant', gx: 1703, gy: 4125, name: "Forgeron d'Armes",                  desc: "Forgeron des Armes pour Débutants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#arme' },
    { id: 'm1a2',  type: 'artisant', gx: 1703, gy: 4125, name: "Forgeron d'Armures",                desc: "Forgeron des Armures pour Débutants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#armure' },
    { id: 'm1a3',  type: 'artisant', gx: 1703, gy: 4125, name: "Forgeron d'Accessoires",            desc: "Forgeron des Accessoires pour Débutants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#accessoires-base' },
    { id: 'm1a4',  type: 'artisant', gx: 1721, gy: 4605, name: 'Marchand Étrange',                  desc: "Marchand suspect trainant derrière la Cathédrale", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#marchand-etrange' },
    { id: 'm1a5',  type: 'artisant', gx: 1725, gy: 4672, name: "Forgeron d'Accessoires en Cuivre",  desc: "Forgeron des Accessoires en Cuivre pour Débutants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#accessoires-cuivre' },
    { id: 'm1a6',  type: 'artisant', gx: 1725, gy: 4672, name: "Forgeron d'Accessoires en Fer",     desc: "Forgeron des Accessoires en Fer pour Débutants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#accessoires-fer' },
    { id: 'm1a7',  type: 'artisant', gx: 1725, gy: 4672, name: 'Refaçonneur',                       desc: "Permet la fabrication de ficelle en tout genre", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/refaconneurs#ville-de-depart' },
    { id: 'm1a8',  type: 'artisant', gx: 2322, gy: 3560, name: 'Forgeron de Lingots',               desc: "Forgeron de Lingots de Cuivre et de Fer", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#lingots' },
    { id: 'm1a9',  type: 'artisant', gx: 3158, gy: 1506, name: "Forgeron d'Armes",                  desc: "Forgeron des Armes pour Confirmés", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#arme-1' },
    { id: 'm1a10', type: 'artisant', gx: 3158, gy: 1506, name: "Forgeron d'Armures",                desc: "Forgeron des Armures pour Confirmés", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#armure-1' },
    { id: 'm1a11', type: 'artisant', gx: 2355, gy: 2412, name: "Forgeron d'Armes",                  desc: "Forgeron d'Armes du Donjon du Labyrinthe des Déchus", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#arme-2' },
    { id: 'm1a12', type: 'artisant', gx: 2355, gy: 2412, name: "Forgeron d'Armures",                desc: "Forgeron d'Armures du Donjon du Labyrinthe des Déchus", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/forgerons#armure-2' },
    { id: 'm1a13', type: 'artisant', gx: 2394, gy: 4293, name: 'Bucheron',                          desc: "Bucheron permettant la Réalisation de Planches", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/bucherons#ville-de-depart' },
    { id: 'm1a14', type: 'artisant', gx: 1712, gy: 4091, name: 'Alchimiste',                        desc: "Alchimiste permettant la Réalisation de Potions et Cristaux", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/alchimistes#ville-de-depart' },
    { id: 'm1a15', type: 'artisant', gx: 3257, gy: 1626, name: 'Alchimiste',                        desc: "Alchimiste permettant la Réalisation de Potions et Cristaux", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/alchimistes#tolbana' },

    { id: 'm1b1',  type: 'repreneur_butin', gx: 1720, gy: 4170, name: 'Repreneur des Débutants',       desc: "Achète des ressources digne d'un Débutant", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/repreneurs-de-butins#ville-de-depart' },
    { id: 'm1b2',  type: 'repreneur_butin', gx: 1446, gy: 3415, name: 'Repreneur de la Forêt',         desc: "Achète des ressources de la Forêt", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/repreneurs-de-butins#hanaka' },
    { id: 'm1b3',  type: 'repreneur_butin', gx: 3074, gy: 3678, name: 'Repreneur Champêtre',           desc: "Achète des ressources des Champs", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/repreneurs-de-butins#mizunari' },
    { id: 'm1b4',  type: 'repreneur_butin', gx: 363,  gy: 3092, name: 'Repreneur des Maraicages',      desc: "Achète des ressources Gluantes", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/repreneurs-de-butins#vallaht' },
    { id: 'm1b5',  type: 'repreneur_butin', gx: 1541, gy: 1983, name: 'Repreneur des Mers',            desc: "Achète des ressources Maritimes", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/repreneurs-de-butins#virelune' },
    { id: 'm1b6',  type: 'repreneur_butin', gx: 2764, gy: 4680, name: 'Repreneur de Squelette',        desc: "Achète des ressources venant des Morts", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/repreneurs-de-butins#chateau-abandonne' },
    { id: 'm1b7',  type: 'repreneur_butin', gx: 3217, gy: 1645, name: 'Repreneur Agguerie de Tolbana', desc: "Achète des ressources digne d'un Combattant Agguerie", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/repreneurs-de-butins#tolbana' },

    { id: 'm1m1',  type: 'marchand', gx: 1720, gy: 4147, name: "Marchand d'Équipement",    desc: "Vends des Armes et objets pour les Nouveaux Arrivants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#ville-de-depart' },
    { id: 'm1m2',  type: 'marchand', gx: 1447, gy: 3390, name: "Marchand d'Équipement",    desc: "Vends des Armes et objets pour les Nouveaux Arrivants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#hanaka' },
    { id: 'm1m3',  type: 'marchand', gx: 438,  gy: 3077, name: "Marchand d'Accessoires",   desc: "Vends des Accessoires Gluants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#vallhat' },
    { id: 'm1m4',  type: 'marchand', gx: 3241, gy: 1626, name: "Marchand d'Accessoires",   desc: "Vends des Accessoires Résistants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#tolbana-1' },
    { id: 'm1m5',  type: 'marchand', gx: 1750, gy: 4147, name: "Marchand d'Outils",        desc: "Vends des outils pour récolter des matières premières", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#ville-de-depart-1' },
    { id: 'm1m6',  type: 'marchand', gx: 1537, gy: 1958, name: "Marchand d'Outils",        desc: "Vends des outils pour récolter des matières premières", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#virelune' },
    { id: 'm1m7',  type: 'marchand', gx: 1940, gy: 843,  name: "Marchand d'Outils",        desc: "Vends des outils pour récolter des matières premières", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#tolbana-3' },
    { id: 'm1m8',  type: 'marchand', gx: 3230, gy: 1658, name: "Marchand de Consommables", desc: "Vends des Utilitaires comme des Potions ou des Parchemins", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#tolbana-2' },
    { id: 'm1m9',  type: 'marchand', gx: 3240, gy: 1658, name: "Marchand d'Équipement",    desc: "Vends des Armes et objets", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#tolbana' },
    { id: 'm1m10', type: 'marchand', gx: 3257, gy: 1638, name: "Marchand d'Outils",        desc: "Vends des outils pour récolter des matières premières", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#candelia' },
    { id: 'm1m10', type: 'marchand', gx: 3071, gy: 3700, name: "Marchand d'Outils",        desc: "Vends des outils pour récolter des matières premières", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/marchands#mizunari' },

    { id: 'm1c1', type: 'clef', emoji: '🗝️', gx: 1750, gy: 4170, name: 'Clef du Donjon Mine de Geldorak',      desc: "Clef permettant d'ouvrir la porte du Donjon des Mines de Geldorak",     link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/fabricants-clefs-et-secret#ville-de-depart' },
    { id: 'm1c2', type: 'clef', emoji: '🗝️', gx: 4210, gy: 3895, name: 'Clef du Donjon Mine de Geldorak',      desc: "Clef permettant d'ouvrir la porte du Donjon des Mines de Geldorak",     link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/fabricants-clefs-et-secret#mine-de-geldorak' },
    { id: 'm1c3', type: 'clef', emoji: '🗝️', gx: 2314, gy: 2435, name: 'Clef du Donjon Labyrinthe des Déchus', desc: "Clef permettant d'ouvrir la porte du Donjon du Labyrinthe des Déchus", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/fabricants-clefs-et-secret#labyrinthe-des-dechus' },
    { id: 'm1c4', type: 'clef', emoji: '🗝️', gx: 955,  gy: 1212, name: "Clef du Donjon Xal'Zirith",            desc: "Clef permettant d'ouvrir la porte du Donjon Xal'Zirith",                link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/fabricants-clefs-et-secret#xalzirith' },
    { id: 'm1c5', type: 'clef', emoji: '🗝️', gx: 1936, gy: 835,  name: "Clef du Donjon Xal'Zirith",            desc: "Clef permettant d'ouvrir la porte du Donjon Xal'Zirith",                link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/fabricants-clefs-et-secret#candelia' },
    { id: 'm1c6', type: 'clef', emoji: '💍', gx: 4128, gy: 1823, name: "Fabricant Secret de l'Ours",           desc: "Permet la confection Secrète du Bracelet de Glace",     link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/fabricants-clefs-et-secret#citadelle-des-neiges' },
    { id: 'm1c7', type: 'clef', emoji: '💍', gx: 1267, gy: 2140, name: 'Fabricant Secret du Léviathan',        desc: "Permet la confection Secrète de l'Anneau du Léviathan", link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/fabricants-clefs-et-secret#antre-de-aepep' },
    { id: 'm1c8', type: 'clef', emoji: '💍', gx: 387,  gy: 3097, name: 'Fabricant Secret des Slimes',          desc: "Permet la confection Secrète de l'Anneau Gluant",       link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/fabricants-clefs-et-secret#vallhat' },
    { id: 'm1c9', type: 'clef', emoji: '💍', gx: 1092, gy: 1193, name: "Fabricant Secret des Araignées",       desc: "Permet la confection Secrète du Collier d'Aragorn",     link: 'https://guilde-sao.gitbook.io/watchers/paliers/carte/personnages/fabricants-clefs-et-secret#arakhnol' },

    { id: 'm1s1',  type: 'quête_secondaire',  gx: 1819, gy: 4002, name: "Tilda",                         desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/tilda' },
    { id: 'm1s2',  type: 'quête_secondaire',  gx: 1817, gy: 3971, name: "Lila",                          desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/lila' },
    { id: 'm1s3',  type: 'quête_secondaire',  gx: 2000, gy: 4280, name: "Varn",                          desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/varn' },
    { id: 'm1s4',  type: 'quête_secondaire',  gx: 1682, gy: 4720, name: "Orin",                          desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/ori' },
    { id: 'm1s5',  type: 'quête_secondaire',  gx: 1682, gy: 4720, name: "Inari",                         desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/inari' },
    { id: 'm1s6',  type: 'quête_secondaire',  gx: 1210, gy: 4296, name: "Meiko",                         desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/meiko' },
    { id: 'm1s7',  type: 'quête_secondaire',  gx: 1214, gy: 4313, name: "Saria",                         desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/saria' },
    { id: 'm1s8',  type: 'quête_secondaire',  gx: 1493, gy: 4306, name: "Rikyu",                         desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/rikyu' },
    { id: 'm1s9',  type: 'quête_secondaire',  gx: 1473, gy: 4321, name: "Bunta",                         desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/bunta' },
    { id: 'm1s10',  type: 'quête_secondaire', gx: 1579, gy: 4037, name: "Nacht",                        desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/nacht' },
    { id: 'm1s11',  type: 'quête_secondaire', gx: 2143, gy: 4177, name: "Millia",                       desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/ville-de-depart/millia' },
    { id: 'm1s12',  type: 'quête_secondaire', gx: 1475, gy: 3373, name: "Genzo",                        desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/hanaka/genzo' },
    { id: 'm1s13',  type: 'quête_secondaire', gx: 1462, gy: 3373, name: "Bartok",                       desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/hanaka/bartok' },
    { id: 'm1s14',  type: 'quête_secondaire', gx: 1377, gy: 3406, name: "Greta",                        desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/hanaka/greta' },
    { id: 'm1s15',  type: 'quête_secondaire', gx: 1351, gy: 3433, name: "Soeur Therra",                 desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/hanaka/soeur-therra' },
    { id: 'm1s16',  type: 'quête_secondaire', gx: 1435, gy: 3532, name: "Rina",                         desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/hanaka/rina' },
    { id: 'm1s17',  type: 'quête_secondaire', gx: 1446, gy: 3560, name: "Maya",                         desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/hanaka/maya' },
    { id: 'm1s18',  type: 'quête_secondaire', gx: 1296, gy: 3438, name: "Toban",                        desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/hanaka/toban' },
    { id: 'm1s19',  type: 'quête_secondaire', gx: 3317, gy: 2954, name: "Fira",                         desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/camp-militaire/fira' },
    { id: 'm1s20',  type: 'quête_secondaire', gx: 3216, gy: 2913, name: "Corentin",                     desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/camp-militaire/corentin' },
    { id: 'm1s21', type: 'quête_secondaire',  gx: 3146, gy: 2898, name: "Jean",                          desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/camp-militaire/jean' },
    { id: 'm1s22', type: 'quête_secondaire',  gx: 3011, gy: 1918, name: "Horace",                        desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/tolbana/horace' },
    { id: 'm1s23', type: 'quête_secondaire',  gx: 1807, gy: 2127, name: "Haruto",                        desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/virelune/haruto' },
    { id: 'm1s24', type: 'quête_secondaire',  gx: 1838, gy: 2019, name: "Sam",                           desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/virelune/sam' },
    { id: 'm1s25', type: 'quête_secondaire',  gx: 1506, gy: 1980, name: "Juliette",                      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/virelune/juliette' },
    { id: 'm1s26', type: 'quête_secondaire',  gx: 1500, gy: 2015, name: "Monique",                       desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/virelune/monique' },
    { id: 'm1s27', type: 'quête_secondaire',  gx: 1565, gy: 1860, name: "Luc",                           desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/virelune/luc' },
    { id: 'm1s28', type: 'quête_secondaire',  gx: 1645, gy: 1042, name: "Gilbert",                       desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/candelia/gilbert' },
    { id: 'm1s29', type: 'quête_secondaire',  gx: 1958, gy: 901,  name: "Pierre",                        desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/candelia/pierre' },
    { id: 'm1s30', type: 'quête_secondaire',  gx: 1952, gy: 859,  name: "Yannis",                        desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/candelia/yannis' },
    { id: 'm1s31', type: 'quête_secondaire',  gx: 1927, gy: 863,  name: "Roméo",                         desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/candelia/roméo' },
    { id: 'm1s32', type: 'quête_secondaire',  gx: 1895, gy: 848,  name: "Tomoko",                        desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/candelia/tomoko' },
    { id: 'm1s33', type: 'quête_secondaire',  gx: 1891, gy: 814,  name: "Gilmar",                        desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/candelia/gilmar' },
    { id: 'm1s34', type: 'quête_secondaire',  gx: 1815, gy: 777,  name: "Émilie",                        desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/candelia/emilie' },
    { id: 'm1s35', type: 'quête_secondaire',  gx: 3077, gy: 3711, name: "Phares",                        desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/mizunari/phares' },
    { id: 'm1s36', type: 'quête_secondaire',  gx: 3060, gy: 3692, name: "Louise",                        desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/mizunari/louise' },
    { id: 'm1s37', type: 'quête_secondaire',  gx: 3038, gy: 3699, name: "Elwyn",                         desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/mizunari/elwyn' },
    { id: 'm1s38', type: 'quête_secondaire',  gx: 3050, gy: 3661, name: "Michelle",                      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/mizunari/michelle' },
    { id: 'm1s39', type: 'quête_secondaire',  gx: 3069, gy: 3668, name: "Martine",                       desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/mizunari/martine' },
    { id: 'm1s40', type: 'quête_secondaire',  gx: 455,  gy: 3066, name: "Par les Branches des Anciens",  desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/vallhat/par-les-branches-des-anciens' },
    { id: 'm1s41', type: 'quête_secondaire',  gx: 442,  gy: 3029, name: "Saya",                          desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/vallhat/saya' },
    { id: 'm1s42', type: 'quête_secondaire',  gx: 416,  gy: 3008, name: "Ayaka",                         desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/vallhat/ayaka' },
    { id: 'm1s43', type: 'quête_secondaire',  gx: 382,  gy: 3046, name: "Daiki",                         desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-secondaires/vallhat/daiki' },

    { id: 'm1p1',  type: 'quête_principale', gx: 1746,  gy: 3643, name: "1 - Un nouveau départ",             desc: "Parlez à Abraham et éliminez des Sangliers corrompues", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/un-nouveau-depart' },
    { id: 'm1p2',  type: 'quête_principale', gx: 1502,  gy: 3408, name: "2 - La vieille Mara",               desc: "Parlez à Mara pour y entendre ses visions", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/la-vieille-mara' },
    { id: 'm1p3',  type: 'quête_principale', gx: 1380,  gy: 3094, name: "3 - La Corruption",                 desc: "Trouvez l'origine des visions de la Vielle Mara", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/la-corruption' },
    { id: 'm1p4',  type: 'quête_principale', gx: 1776,  gy: 4516, name: "4 - Revenir plus Fort",             desc: "Entrainez vous et allez à la rencontre du Maître Épéiste", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/revenir-plus-fort' },
    { id: 'm1p5',  type: 'quête_principale', gx: 3059,  gy: 3655, name: "5 - L'Aventure Commence",           desc: "Dirigez vous à Mizunari afin de compléter vos premiers exploits en tant qu'aventurier", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/laventure-commence' },
    { id: 'm1p6',  type: 'quête_principale', gx: 3258,  gy: 3781, name: "6 - Le ravage des Nephentes",       desc: "Trouvez Harrold le mari d'Elma", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/le-ravage-des-nephentes' },
    { id: 'm1p7',  type: 'quête_principale', gx: 2767,  gy: 2995, name: "7 - Velka",                         desc: "Allez à la rencontre de Velka", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/velka' },
    { id: 'm1p8',  type: 'quête_principale', gx: 2791,  gy: 4484, name: "8 - Les Ruines Maudites",           desc: "Cherchez Erik qui vous a été recommandé par Velka", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/les-ruines-maudites' },
    { id: 'm1p9',  type: 'quête_principale', gx: 2709,  gy: 4408, name: "9 - Le Donjon des Ruines Maudites", desc: "Récupérez de quoi rentrer dans le Sous-Donjon Nasgul", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/le-donjon-des-ruines-maudites' },
    { id: 'm1p10', type: 'quête_principale', gx: 2709,  gy: 4408, name: "10 - Nasgul: Protecteur Maudit",    desc: "Cherchez le Spectre Archiviste qui vous expliquera comment défaire le Maître du Donjon, et vennez en à bout!", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/nasgul-protecteur-maudit' },
    { id: 'm1p11', type: 'quête_principale', gx: 4210,  gy: 3895, name: "11 - Donjon: Mine de Geldorak",     desc: "Venez à bout du Donjon Geldorak", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/donjon-mine-de-geldorak' },
    { id: 'm1p12', type: 'quête_principale', gx: 1776,  gy: 4516, name: "12 - Retour à la Cathédrale",       desc: "Retournez voir le Maître Épéiste", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/retour-a-la-cathedrale' },
    { id: 'm1p13', type: 'quête_principale', gx: 377,   gy: 3063, name: "13 - L'Homme à capuche",            desc: "Demandez aux habitants de Vallhat si ils savent où se trouve un mystérieux homme à capuche", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/lhomme-a-capuche' },
    { id: 'm1p14', type: 'quête_principale', gx: 248,   gy: 3204, name: "14 - Gorbel: Slime Imposant",       desc: "Venez à bout du terrible slime et fouillez l'homme à capuche", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/gorbel-slime-imposant' },
    { id: 'm1p15', type: 'quête_principale', gx: 1776,  gy: 4516, name: "15 - De Retour à la Cathédrale",    desc: "Allez une nouvelle fois raconter vos péripéties au Maître Épéiste", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/de-retour-a-la-cathedrale' },
    { id: 'm1p16', type: 'quête_principale', gx: 2315,  gy: 2435, name: "16 - Le Sceau des Anciens",         desc: "Allez voir Catherine, qui vous permettra de reconstruire le Sceau des Anciens", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/le-sceau-des-anciens' },
    { id: 'm1p17', type: 'quête_principale', gx: 2315,  gy: 2435, name: "17 - Wali",                         desc: "Parlez à Wali", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/wali' },
    { id: 'm1p18', type: 'quête_principale', gx: 3125,  gy: 1470, name: "18 - Méphisto",                     desc: "Parlez au Maître de Wali", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/mephisto' },
    { id: 'm1p19', type: 'quête_principale', gx: 3119,  gy: 1506, name: "19 - Wali l'Apprenti",              desc: "Donnez à Wali les informations donné de Méphisto afin de continuer votre aventure", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/wali-lapprenti' },
    { id: 'm1p20', type: 'quête_principale', gx: 3158,  gy: 1506, name: "20 - La Base du Parchemin",         desc: "Ramenez à Émy les matériaux pour concevoir la Base du Parchemin permettant l'ouverture de la Tour du Kobold", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/la-base-du-parchemin' },
    { id: 'm1p21', type: 'quête_principale', gx: 1510,  gy: 1997, name: "21 - Ramoon",                       desc: "Parlez à Ramoon", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/ramoon' },
    { id: 'm1p22', type: 'quête_principale', gx: 3252,  gy: 1655, name: "22 - Chasse aux Poissons Requin",   desc: "Parlez à Malrik qui vous demandera de tuer des Poissons Requin à Virelune", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/chasse-aux-poissons-requin' },
    { id: 'm1p23', type: 'quête_principale', gx: 1354,  gy: 2149, name: "23 - Nymbréa: l'Ombre du Lac",      desc: "Tuer le Léviathan Nymbréa", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/nymbrea-lombre-du-lac' },
    { id: 'm1p24', type: 'quête_principale', gx: 955,   gy: 1212, name: "24 - Sanctuaire de Xal'Zirith",     desc: "Parlez à Silrix", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/sanctuaire-de-xalzirith' },
    { id: 'm1p25', type: 'quête_principale', gx: 3158,  gy: 1506, name: "25 - Retour à Tolbana",             desc: "Retournez voir Émy pour qu'elle améliore votre Parchemin avec tout vos nouveaux matériaux", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/retour-a-tolbana' },
    { id: 'm1p26', type: 'quête_principale', gx: 3125,  gy: 1470, name: "26 - Le Parchemin de Sceau",        desc: "Retournez voir Méphisto", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/le-parchemin-de-sceau' },
    { id: 'm1p27', type: 'quête_principale', gx: 3182,  gy: 1422, name: "27 - Le Tombeau des Harald",        desc: "Allez voir le Roi de Tolbana, afin qu'il vous donne accès à la tombe de ses ancêtres et bénissent votre Parchemin pour ouvrir les Portes de la Tour du Kobold", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/e-tombeau-des-harald' },
    { id: 'm1p28', type: 'quête_principale', gx: 3182,  gy: 1422, name: "28 - Donjon: Le Kobold",            desc: "Retournez voir le roi Harald et menez une expédition punitive, afin de défaire le roi Kobold: Illfang", link: 'https://guilde-sao.gitbook.io/watchers/paliers/quetes/quetes-principales/donjon-le-kobold' },
  
  ],
  2: [
    { id: 'm2d1',  type: 'donjon',  gx: 473, gy: -669, name: 'Donjon Ruche de Melliona',                  desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/donjons/donjon-ruche-de-melliona' },

    { id: 'm2r1',  type: 'région',  gx: 118, gy: -68, name: 'Lac des Taureaux',                           desc: "Un lac asséché, dont le sol craquelé est parcouru des taureaux errants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/lac-des-taureaux' },
    { id: 'm2r2',  type: 'région',  gx: 64, gy: -348, name: 'Urbus',                                      desc: "Ville marchande prospère, garde l'entrée du palier avec ses étals animés", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/urbus' },
    { id: 'm2r3',  type: 'région',  gx: -545, gy: -245, name: 'Kaelor',                                   desc: "Ville fortifié, imprenable et dévouée au Dieu de la Guerre", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/kaelor' },
    { id: 'm2r4',  type: 'région',  gx: -389, gy: -493, name: 'Désert des Crocs Argentés',                desc: "Un désert impitoyable où rodent des loups aux crocs argentés", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/monstres/carte/desert_des_crocs_argentes' },
    { id: 'm2r5',  type: 'région',  gx: 445, gy: -611, name: 'Forêt Sucrée',                              desc: "Une forêt parfumée de miel, habitée par des ours et le bourdonnement des abeilles", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/regions/foret-sucree' },
    { id: 'm2r6',  type: 'région',  gx: 473, gy: -669, name: 'Ruche de Melliona',                         desc: "Une ruche géante et bourdonnante, royaume de Melliona et ses abeilles", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/regions/ruche-de-melliona' },
    { id: 'm2r7',  type: 'région',  gx: -525, gy: 444, name: 'Forêt des Ailes d\'Émeraude',               desc: "Une forêt luxuriante, refuge des harpies aux ailes vertes émeraude", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/regions/foret-des-ailes-demeraude' },
    { id: 'm2r8',  type: 'région',  gx: -780, gy: 171, name: 'Baie des Monstres Ondoyante',               desc: "Un marais tourbillonnant habité par des harpies de foudre aux cris perçants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/regions/baie-des-monstres-ondoyante' },
    { id: 'm2r9',  type: 'région',  gx: -6, gy: 181, name: 'Sanctuaire de Khesûn',                        desc: "Un sanctuaire abandonné dans le désert, peuplé de squelettes", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/regions/sanctuaire-de-khesun' },
    { id: 'm2r10',  type: 'région',  gx: 798, gy: 253, name: 'Oasis Secret',                              desc: "Une oasis secrète où des pécheurs vivent au rythme de l'eau et du silence", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/regions/oasis-secret' },
    { id: 'm2r11',  type: 'région',  gx: -88, gy: -92, name: 'Baobab Millénaire',                         desc: "Un baobab millénaire aux racines géantes, gardien silencieux du temps et des légendes", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/regions/baobab-millenaire' },
    { id: 'm2r12',  type: 'région',  gx: 524, gy: -435, name: 'Autel des Deux Lunes',                     desc: "Personne ne détient d'information liée à ce lieu. Simplement deux autels ^portant une lune chacune...", link: 'http://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/regions/autel-des-deux-lunes' },
    { id: 'm2r13',  type: 'région',  gx: -397, gy: 256, name: 'Taran',                                    desc: "Ville abandonné dans un caillou", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/regions/taran' },
    { id: 'm2r14',  type: 'région',  gx: 671, gy: -255, name: 'Marome',                                   desc: "Petit village de marchands autosuffisant, uni par les prières à la déesse maternelle", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/regions/marome' },
    { id: 'm2r15',  type: 'région',  gx: -390, gy: -400, name: 'Maisons des Ngangas',                     desc: "Maisons de Kwabeno et Kwabena, deux ermites perdus des montagnes", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/regions/maisons-des-ngangas' },
    { id: 'm2r16',  type: 'région',  gx: -150, gy: 740, name: 'Tour de Taurus',                           desc: "Une tour massive où résonnent les pas de Taurus, le Roi taureau redoutable", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/regions/tour-de-taurus' },

    { id: 'm2t1',  type: 'ressource', emoji: '🌳', gx: -88, gy: -92, name: 'Acacia',                      desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/ressources/bucheron#acacia' },
    { id: 'm2t2',  type: 'ressource', emoji: '🌾', gx: -432, gy: 308, name: 'Sépal d\'Ambre',             desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/ressources/herboriste#sepal-dambre' },
    { id: 'm2t3',  type: 'ressource', emoji: '🌾', gx: -432, gy: 308, name: 'Épine d\'Oracile',           desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/ressources/herboriste#epine-doracile' },
    { id: 'm2t3',  type: 'ressource', emoji: '🌾', gx: 84, gy: 248, name: 'Épine d\'Oracile',             desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/ressources/herboriste#epine-doracile' },
    { id: 'm2t3',  type: 'ressource', emoji: '🌾', gx: 491, gy: -97, name: 'Épine d\'Oracile',            desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/ressources/herboriste#epine-doracile' },

    { id: 'm2b1',  type: 'repreneur_butin', gx: 64, gy: -321, name: 'Repreneur des Ressources aux abords de Urbus',          desc: "Achète des ressources digne d'un Débutant", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/repreneurs-de-butins#urbus' },
    { id: 'm2b2',  type: 'repreneur_butin', gx: -530, gy: -239, name: 'Repreneur des Ressources des Harpies',                desc: "Achète des ressources digne d'un Débutant", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/repreneurs-de-butins#kaelor' },
    { id: 'm2b3',  type: 'repreneur_butin', gx: 665, gy: -256, name: 'Repreneur des Ressources du Sanctuaire de Khesûn',     desc: "Achète des ressources digne d'un Débutant", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/repreneurs-de-butins#marome' },

    { id: 'm2c1', type: 'clef', emoji: '🗝️', gx: 150, gy: -290,  name: "Clef du Donjon Ruche de Melliona",                  desc: "Clef permettant d'ouvrir la porte du Donjon Ruche de Melliona",                link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/fabricants-clefs-et-secrets#urbus-melliona' },
    { id: 'm2c1', type: 'clef', emoji: '🗝️', gx: 150, gy: -290,  name: "Clef du Donjon Tombeau du Nécromancien",            desc: "Clef permettant d'ouvrir la porte du Donjon Tombeau du Nécromancien",                link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/fabricants-clefs-et-secrets#urbus-tombeau-du-necromancien' },
    { id: 'm2c3', type: 'clef', emoji: '💍', gx: 72, gy: -45, name: "Fabricant Secret des Taureaux",                         desc: "Permet la confection Secrète du Talisman Féroce",     link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/fabricants-clefs-et-secrets#lac-des-taureaux' },
    { id: 'm2c4', type: 'clef', emoji: '💍', gx: -761, gy: 88, name: "Fabricant Secret de la Harpie Noyé",                   desc: "Permet la confection Secrète de l'Anneau de la Harpie Noyée",     link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/fabricants-clefs-et-secrets#baie-des-monstres-ondoyante' },
    { id: 'm2c5', type: 'clef', emoji: '💍', gx: -571, gy: 480, name: "Fabricant Secret de la Harpie Écrasée",               desc: "Permet la confection Secrète de l'Anneau de la Harpie Écrasée",     link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/fabricants-clefs-et-secrets#foret-des-ailes-demeraude' },
    { id: 'm2c5', type: 'clef', emoji: '💍', gx: -43, gy: 188, name: "Fabricant Secret du Sanctuaire",                       desc: "Permet la confection Secrète du Collier Runique",     link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/fabricants-clefs-et-secrets#sanctuaire-de-khesun' },
	{ id: 'm2c6', type: 'clef', emoji: '💍', gx: -662, gy: -84, name: "Fabricant Secret de la Corruption",                    desc: "Permet la confection Secrète du très puissant Masque Corrompu",     link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/~/changes/107/carte/personnages/fabricants-clefs-et-secrets#corruption' },

    { id: 'm2m1',  type: 'marchand', gx: -538, gy: -262, name: "Marchand d'Équipement",    desc: "Vends des Armes et objets pour les Nouveaux Arrivants", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/marchands#kaelor' },
    { id: 'm2m2',  type: 'marchand', gx: -527, gy: -262, name: "Marchand d'Accessoires",   desc: "Vends des Accessoires de la faune du Palier 2", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/marchands#kaelor-1' },
    { id: 'm2m3',  type: 'marchand', gx: -543, gy: -258, name: "Marchand d'Outils",        desc: "Vends des outils pour récolter des matières premières", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/marchands#kaelor-2' },

    { id: 'm2a1', type: 'artisant',  gx: -527, gy: -274, name: 'Alchimiste',               desc: "Alchimiste permettant la Réalisation de Potions et Cristaux", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/alchimistes#kaelor' },
    { id: 'm2a2', type: 'artisant',  gx: -538, gy: -274, name: 'Bucheron',                 desc: "Bucheron permettant la Réalisation de Planches", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/bucherons#kaelor' },
    { id: 'm2a3', type: 'artisant',  gx: 2,    gy: -332, name: 'Refaçonneur',              desc: "Permet la fabrication de ficelle en tout genre", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/refaconneurs#urbus' },
    { id: 'm2a4', type: 'artisant',  gx: 107,  gy: -387, name: 'Forgeron d\'Accessoires',  desc: "Permet la fabrication d'Accessoires puissant", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/forgerons#urbus-accessoires' },
    { id: 'm2a5', type: 'artisant',  gx: 117,  gy: -358, name: 'Forgeron de Lingots',      desc: "Permet la fabrication de lingots de Bauxite et d'Onyx Impur", link: '' },
    { id: 'm2a6', type: 'artisant',  gx: 807, gy: -271, name: 'Forgeron de Lingots',      desc: "Permet la fabrication de lingots d'Onyx Pur", link: '' },
    { id: 'm2a7', type: 'artisant',  gx: -559, gy: -265, name: 'Forgeron d\'Accessoires',  desc: "Permet la fabrication d'Accessoires des Ours et du Taureau", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/forgerons#kaelor-accessoires' },
    { id: 'm2a8', type: 'artisant',  gx: -722, gy: 20,   name: 'Forgeron d\'Accessoires',  desc: "Permet la fabrication d'Accessoires de Feraille", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/forgerons#accessoires-ferraile' },
    { id: 'm2a9', type: 'artisant',  gx: -184, gy: 23,   name: 'Forgeron d\'Accessoires',  desc: "Permet la fabrication d'Accessoires de Bauxite", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/forgerons#accessoires-bauxite' },
    { id: 'm2a10',type: 'artisant',  gx: -464, gy: 313,   name: 'Forgeron d\'Accessoires',  desc: "Permet la fabrication d'Accessoires d'Onyx Impur", link: '' },

    { id: 'm2s1',  type: 'quête_secondaire',  gx: 106, gy: -364, name: "L'Art des Plumes",                         desc: "Ramenez 4 plumes de chaque Harpies à Ifa", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/urbus/lart-des-plumes' },
    { id: 'm2s2',  type: 'quête_secondaire',  gx: 96, gy: -355, name: "L'Art des Plumes",                         desc: "Ramenez différentes peaux de monstres à Ife", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/urbus/lart-des-peaux' },
    { id: 'm2s3',  type: 'quête_secondaire',  gx: 107, gy: -283, name: "Ma première Arme",                         desc: "Ramenez de quoi confectionner une épée à Charles", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/urbus/ma-premiere-arme' },
    { id: 'm2s4',  type: 'quête_secondaire',  gx: -188, gy: -640, name: "L'Épreuve du Chasseur",                         desc: "Montrer à Typpe de quoi vous êtres capable et défaire tout les Boss du Palier 2", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/urbus/lepreuve-du-chasseur' },
    { id: 'm2s5',  type: 'quête_secondaire',  gx: -514, gy: -245, name: "Le chat Relax",                         desc: "Retrouver le chat Relax et donnez le à Itami", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/kaelor/le-chat-relax' },
    { id: 'm2s6',  type: 'quête_secondaire',  gx: -566, gy: -231, name: "Aider Yûko",                         desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/kaelor/aider-yuko' },
    { id: 'm2s7',  type: 'quête_secondaire',  gx: -521, gy: -237, name: "Aider à la Cuisine",                         desc: "Aidez Mansa pour sa cuisine", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/kaelor/aide-a-la-cuisine' },
    { id: 'm2s8',  type: 'quête_secondaire',  gx: -544, gy: -228, name: "Le Clocher de la Sombre Messagère",                         desc: "Aidez Nora", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/kaelor/le-clocher-de-la-sombre-messagere' },
    { id: 'm2s9',  type: 'quête_secondaire',  gx: -536, gy: -237, name: "Ça pique, mais ça fait du bien",                         desc: "Ramenez du Miel à Baraka", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/kaelor/ca-pique-mais-ca-fait-du-bien' },
    { id: 'm2s10', type: 'quête_secondaire',  gx: 594, gy: -244, name: "Les Bases d'une Cabane",                         desc: "Ramenez de quoi commencer la cabane de Bronn", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/marome/les-bases-dune-cabane' },
    { id: 'm2s11', type: 'quête_secondaire',  gx: 594, gy: -244, name: "Les Murs d'une Cabane",                         desc: "Ramenez de quoi continuer la cabane de Bronn", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/marome/les-murs-dune-cabane' },
    { id: 'm2s12', type: 'quête_secondaire',  gx: 594, gy: -244, name: "Le Toit d'une Cabane",                         desc: "Ramenez de quoi finir la cabane de Bronn", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/marome/le-toit-dune-cabane' },
    { id: 'm2s13', type: 'quête_secondaire',  gx: 648, gy: -260, name: "Non, c'est de la Sape!",                         desc: "Aidez Minutaire à confectionner des vêtements", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/marome/non-cest-de-la-sape' },
    { id: 'm2s14', type: 'quête_secondaire',  gx: 672, gy: -279, name: "L'Onyx du Savoir",                         desc: "Aidez Shii à faire sa potion", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/marome/lonyx-du-savoir' },
    { id: 'm2s15', type: 'quête_secondaire',  gx: 396, gy: -518, name: "L'empreinte des Seas",                         desc: "Aidez Elyenn à retrouvez ses affaires", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/autel-des-deux-lunes/lempreinte-des-seas' },
    { id: 'm2s16', type: 'quête_secondaire',  gx: -149, gy: 9, name: "Un bon petit Repas",                         desc: "Aidez Havca à cuisiner un ragoût parfumé", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/sanctuaire-de-khesun/un-bon-petit-repas' },
    { id: 'm2s17', type: 'quête_secondaire',  gx: -34, gy: 188, name: "La Philosophie de Bushi",                         desc: "Aidez SamaelTVS à vaincre des Squelettes du Sanctuaire", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/sanctuaire-de-khesun/la-philosophie-de-bushi' },
    { id: 'm2s18', type: 'quête_secondaire',  gx: -34, gy: 188, name: "Un peu de chaque",                         desc: "Aidez Frank à vaincre les 3 types de Harpie", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/taran/un-peu-de-chaque' },
    { id: 'm2s19', type: 'quête_secondaire',  gx: -400, gy: 262, name: "Hater du Vert",                         desc: "Aidez Proris à vainbcre des Harpies de Terre", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/taran/hater-du-vert' },
    { id: 'm2s20', type: 'quête_secondaire',  gx: -403, gy: 252, name: "Nettoyer les cieux de Taran",                         desc: "Aidez Sissou à vaincre des Harpies de Feu ou de Foudre", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-secondaires/taran/nettoyer-les-cieux-de-taran' },

    { id: 'm2p1',  type: 'quête_principale', gx: -17,  gy: -786, name: "1 - Le Pallier 2...",             desc: "Parlez au Maître d'Armes et Sautez dans le lac", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-principales/le-palier-2...' },
    { id: 'm2p2',  type: 'quête_principale', gx: 10,  gy: -612, name: "2 - Parler à la femme étrange",             desc: "Parlez à la femme étrange au bord du Lac", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-principales/parler-a-la-femme-etrange' },
    { id: 'm2p3',  type: 'quête_principale', gx: 128,  gy: -348, name: "3 - Chemin vers Urbus",             desc: "Trouvez Arteron afin de parler de la corruption", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-principales/chemin-vers-urbus' },
    { id: 'm2p4',  type: 'quête_principale', gx: -544,  gy: -238, name: "4 - À la recherche des Ngangas",             desc: "Parler à Bantu", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-principales/a-la-recherche-des-ngangas' },
	{ id: 'm2p5',  type: 'quête_principale', gx: -390, gy: -400, name: "5 - Un joueur doit faire ses preuves",             desc: "Allez à la rencontre des Ngangas", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-principales/un-joueur-doit-faire-ses-preuves' },
	{ id: 'm2p6',  type: 'quête_principale', gx: 698, gy: -217, name: "6 - Communication avec Yaa",             desc: "Communiquer avec une des 3 statues Divine du Palier 2 pour qu'elle vous aide a luter contre la corruption", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-principales/communication-avec-yaa' },
	{ id: 'm2p7',  type: 'quête_principale', gx: 150, gy: -290, name: "7 - Façonneur de Clé I",             desc: "Réalisez le Donjon Ruche de Melliona", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-principales/faconneur-de-cle-i' },
	{ id: 'm2p8',  type: 'quête_principale', gx: 62, gy: -397, name: "8 - Retour a Urbus",             desc: "Allez à la rencontre de la deuxième statue divine après avoir informer le Maître Épéiste de votre avancé", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-principales/retour-a-urbus' },
	{ id: 'm2p9',  type: 'quête_principale', gx: 150, gy: -290, name: "9 - Donjon: Le Tombeau Oublié",             desc: "Réalisez le Donjon Tombeau du Nécromancien", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-principales/donjon-le-tombeau-oublie' },
	{ id: 'm2p10', type: 'quête_principale', gx: -586, gy: -280, name: "10 - Le Tribut avant le Verdict",             desc: "Convoquez la dernière statue divine afin qu'elle vous aide", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-principales/le-tribut-avant-le-verdict' },
	{ id: 'm2p11', type: 'quête_principale', gx: 62, gy: -397, name: "11 - La Facette de la Réalité",             desc: "Faites votre rapport au Maître Épéiste sur la corruption", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-principales/la-facette-de-la-realite' },
	{ id: 'm2p12', type: 'quête_principale', gx: -472, gy: -57, name: "12 - Le Rituel de Purification",             desc: "C'est le grand moment, invoquez les 3 statues divine afin qu'elle vous donne de quoi affronter le puissant Astérius!", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/quetes/quetes-principales/le-rituel-de-purification' },
  ],
  
};

const FLOOR_MARKERS_UNDERGROUND = {
  2: [
    { id: 'm2d1u1',  type: 'donjon',  gx: 673, gy: 227, name: 'Donjon Tombeau du Nécromancien',           desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/donjons/donjon-tombeau-du-necromancien' },

    { id: 'm2r1u1',  type: 'région',  gx: -540, gy: 226, name: 'Nid de Brasier',                          desc: "Un nid enflammé, refuge des harpies de feu au cœur de terres brûlantes", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/regions/nid-de-brasier' },
    { id: 'm2r2u1',  type: 'région',  gx: 210, gy: 288, name: 'Les Veines de Sablemor',                   desc: "Des veines de sable profondes, sombres et étroites, cachant Magnus, le redoutable boss", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/regions/les-veines-de-sablemor' },
    { id: 'm2r3u1',  type: 'région',  gx: -296, gy: -79, name: 'Grotte de Taran',                         desc: "Grotte remplie de minéraux impressionnants et de mystères", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/regions/grotte-de-taran' },
    { id: 'm2r4u1',  type: 'région',  gx: 673, gy: 227, name: 'Tombeau du Nécromancien',                  desc: "Un nécromancien repose dans un tombeau secret, enfoui au cœur d'un labyrinthe désertique", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/regions/tombeau-du-necromancien' },

    { id: 'm2t1u1', type: 'ressource', emoji: '⛏️', gx: -362,  gy: -30, name: 'Onyx',                     desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/ressources/mineur#onyx' },
    { id: 'm2t2u1', type: 'ressource', emoji: '⛏️', gx: -206,  gy: -185, name: 'Bauxite',                 desc: "", link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/ressources/mineur#bauxite' },

    { id: 'm2c1u1', type: 'clef', emoji: '💍', gx: -645, gy: 179, name: "Fabricant Secret de la Harpie Enflammée",                     desc: "Permet la confection Secrète de l'Anneau de la Harpie Enflammée",     link: 'https://guilde-sao.gitbook.io/watchers/paliers/palier-2/carte/personnages/fabricants-clefs-et-secrets#nid-de-brasier' },

    { id: 'm1a1u1',type: 'artisant',  gx: 304, gy: 464,   name: 'Forgeron d\'Accessoires',                 desc: "Permet la fabrication d'Accessoires d'Onyx Pur", link: '' },
  ],
};

const MAP_CALIBRATION = {
  1: {
    centerPixel: { x: 450,    y: 450  },
    centerGame:  { x: 2474.5, y: 2570 },
    radiusPixel: 450,
    radiusGame:  2474.5,
  },
  2: {
    centerPixel: { x: 450, y: 450 },
    centerGame:  { x: 0,   y: 0   },
    radiusPixel: 450,
    radiusGame:  1000,
  }
};